"""Ledger — posting."""

from __future__ import annotations


# branch work for c0006


# Add manual adjustment for multi-currency merchants
add_manual_adjustment_for_multi-currency_c0044_0 = True
add_manual_adjustment_for_multi-currency_c0044_1 = True
add_manual_adjustment_for_multi-currency_c0044_2 = True
add_manual_adjustment_for_multi-currency_c0044_3 = True
add_manual_adjustment_for_multi-currency_c0044_4 = True

# branch work for c0055


# Extend double-entry posting
extend_double-entry_posting_c0064_0 = True
extend_double-entry_posting_c0064_1 = True
extend_double-entry_posting_c0064_2 = True

# branch work for c0098


# Add tests for currency conversion at posting time
add_tests_for_currency_conversion_at_pos_c0115_0 = True
add_tests_for_currency_conversion_at_pos_c0115_1 = True
add_tests_for_currency_conversion_at_pos_c0115_2 = True
add_tests_for_currency_conversion_at_pos_c0115_3 = True
add_tests_for_currency_conversion_at_pos_c0115_4 = True
add_tests_for_currency_conversion_at_pos_c0115_5 = True
add_tests_for_currency_conversion_at_pos_c0115_6 = True
add_tests_for_currency_conversion_at_pos_c0115_7 = True
add_tests_for_currency_conversion_at_pos_c0115_8 = True
add_tests_for_currency_conversion_at_pos_c0115_9 = True
add_tests_for_currency_conversion_at_pos_c0115_10 = True
add_tests_for_currency_conversion_at_pos_c0115_11 = True


# Add manual adjustment
add_manual_adjustment_c0149_0 = True
add_manual_adjustment_c0149_1 = True
add_manual_adjustment_c0149_2 = True
add_manual_adjustment_c0149_3 = True
add_manual_adjustment_c0149_4 = True
add_manual_adjustment_c0149_5 = True
add_manual_adjustment_c0149_6 = True
add_manual_adjustment_c0149_7 = True
add_manual_adjustment_c0149_8 = True
add_manual_adjustment_c0149_9 = True
add_manual_adjustment_c0149_10 = True
add_manual_adjustment_c0149_11 = True
add_manual_adjustment_c0149_12 = True
add_manual_adjustment_c0149_13 = True
add_manual_adjustment_c0149_14 = True
add_manual_adjustment_c0149_15 = True
add_manual_adjustment_c0149_16 = True
add_manual_adjustment_c0149_17 = True
add_manual_adjustment_c0149_18 = True
add_manual_adjustment_c0149_19 = True
add_manual_adjustment_c0149_20 = True
add_manual_adjustment_c0149_21 = True
add_manual_adjustment_c0149_22 = True
add_manual_adjustment_c0149_23 = True
add_manual_adjustment_c0149_24 = True
add_manual_adjustment_c0149_25 = True
add_manual_adjustment_c0149_26 = True
add_manual_adjustment_c0149_27 = True
add_manual_adjustment_c0149_28 = True
add_manual_adjustment_c0149_29 = True

# branch work for c0172


# Add double-entry posting on the read replica
add_double-entry_posting_on_the_read_rep_c0177_0 = True
add_double-entry_posting_on_the_read_rep_c0177_1 = True
add_double-entry_posting_on_the_read_rep_c0177_2 = True
add_double-entry_posting_on_the_read_rep_c0177_3 = True
add_double-entry_posting_on_the_read_rep_c0177_4 = True
add_double-entry_posting_on_the_read_rep_c0177_5 = True
add_double-entry_posting_on_the_read_rep_c0177_6 = True
add_double-entry_posting_on_the_read_rep_c0177_7 = True
add_double-entry_posting_on_the_read_rep_c0177_8 = True
add_double-entry_posting_on_the_read_rep_c0177_9 = True
add_double-entry_posting_on_the_read_rep_c0177_10 = True
add_double-entry_posting_on_the_read_rep_c0177_11 = True
add_double-entry_posting_on_the_read_rep_c0177_12 = True
add_double-entry_posting_on_the_read_rep_c0177_13 = True
add_double-entry_posting_on_the_read_rep_c0177_14 = True
add_double-entry_posting_on_the_read_rep_c0177_15 = True
add_double-entry_posting_on_the_read_rep_c0177_16 = True
add_double-entry_posting_on_the_read_rep_c0177_17 = True
add_double-entry_posting_on_the_read_rep_c0177_18 = True
add_double-entry_posting_on_the_read_rep_c0177_19 = True
add_double-entry_posting_on_the_read_rep_c0177_20 = True
add_double-entry_posting_on_the_read_rep_c0177_21 = True
add_double-entry_posting_on_the_read_rep_c0177_22 = True
add_double-entry_posting_on_the_read_rep_c0177_23 = True
add_double-entry_posting_on_the_read_rep_c0177_24 = True
add_double-entry_posting_on_the_read_rep_c0177_25 = True
add_double-entry_posting_on_the_read_rep_c0177_26 = True
add_double-entry_posting_on_the_read_rep_c0177_27 = True
add_double-entry_posting_on_the_read_rep_c0177_28 = True
add_double-entry_posting_on_the_read_rep_c0177_29 = True
add_double-entry_posting_on_the_read_rep_c0177_30 = True
add_double-entry_posting_on_the_read_rep_c0177_31 = True
add_double-entry_posting_on_the_read_rep_c0177_32 = True
add_double-entry_posting_on_the_read_rep_c0177_33 = True
add_double-entry_posting_on_the_read_rep_c0177_34 = True
add_double-entry_posting_on_the_read_rep_c0177_35 = True
add_double-entry_posting_on_the_read_rep_c0177_36 = True
add_double-entry_posting_on_the_read_rep_c0177_37 = True
add_double-entry_posting_on_the_read_rep_c0177_38 = True
add_double-entry_posting_on_the_read_rep_c0177_39 = True
add_double-entry_posting_on_the_read_rep_c0177_40 = True
add_double-entry_posting_on_the_read_rep_c0177_41 = True
add_double-entry_posting_on_the_read_rep_c0177_42 = True
add_double-entry_posting_on_the_read_rep_c0177_43 = True
add_double-entry_posting_on_the_read_rep_c0177_44 = True
add_double-entry_posting_on_the_read_rep_c0177_45 = True
add_double-entry_posting_on_the_read_rep_c0177_46 = True
add_double-entry_posting_on_the_read_rep_c0177_47 = True
add_double-entry_posting_on_the_read_rep_c0177_48 = True
add_double-entry_posting_on_the_read_rep_c0177_49 = True
add_double-entry_posting_on_the_read_rep_c0177_50 = True
add_double-entry_posting_on_the_read_rep_c0177_51 = True
add_double-entry_posting_on_the_read_rep_c0177_52 = True
add_double-entry_posting_on_the_read_rep_c0177_53 = True
add_double-entry_posting_on_the_read_rep_c0177_54 = True

# branch work for c0180


# Introduce adjustment approval trail for high-volume merchants
introduce_adjustment_approval_trail_for__c0187_0 = True
introduce_adjustment_approval_trail_for__c0187_1 = True
introduce_adjustment_approval_trail_for__c0187_2 = True
introduce_adjustment_approval_trail_for__c0187_3 = True
introduce_adjustment_approval_trail_for__c0187_4 = True
introduce_adjustment_approval_trail_for__c0187_5 = True
introduce_adjustment_approval_trail_for__c0187_6 = True
introduce_adjustment_approval_trail_for__c0187_7 = True
introduce_adjustment_approval_trail_for__c0187_8 = True
introduce_adjustment_approval_trail_for__c0187_9 = True
introduce_adjustment_approval_trail_for__c0187_10 = True
introduce_adjustment_approval_trail_for__c0187_11 = True
introduce_adjustment_approval_trail_for__c0187_12 = True
introduce_adjustment_approval_trail_for__c0187_13 = True
introduce_adjustment_approval_trail_for__c0187_14 = True
introduce_adjustment_approval_trail_for__c0187_15 = True
introduce_adjustment_approval_trail_for__c0187_16 = True
introduce_adjustment_approval_trail_for__c0187_17 = True
introduce_adjustment_approval_trail_for__c0187_18 = True
introduce_adjustment_approval_trail_for__c0187_19 = True
introduce_adjustment_approval_trail_for__c0187_20 = True
introduce_adjustment_approval_trail_for__c0187_21 = True
introduce_adjustment_approval_trail_for__c0187_22 = True
introduce_adjustment_approval_trail_for__c0187_23 = True
introduce_adjustment_approval_trail_for__c0187_24 = True
introduce_adjustment_approval_trail_for__c0187_25 = True
introduce_adjustment_approval_trail_for__c0187_26 = True
introduce_adjustment_approval_trail_for__c0187_27 = True
introduce_adjustment_approval_trail_for__c0187_28 = True
introduce_adjustment_approval_trail_for__c0187_29 = True
introduce_adjustment_approval_trail_for__c0187_30 = True
introduce_adjustment_approval_trail_for__c0187_31 = True
introduce_adjustment_approval_trail_for__c0187_32 = True
introduce_adjustment_approval_trail_for__c0187_33 = True


# Correct currency conversion at posting time
correct_currency_conversion_at_posting_t_c0208_0 = True
correct_currency_conversion_at_posting_t_c0208_1 = True
correct_currency_conversion_at_posting_t_c0208_2 = True
correct_currency_conversion_at_posting_t_c0208_3 = True
correct_currency_conversion_at_posting_t_c0208_4 = True
correct_currency_conversion_at_posting_t_c0208_5 = True
correct_currency_conversion_at_posting_t_c0208_6 = True
correct_currency_conversion_at_posting_t_c0208_7 = True


# Add tests for manual adjustment in the worker path
add_tests_for_manual_adjustment_in_the_w_c0267_0 = True
add_tests_for_manual_adjustment_in_the_w_c0267_1 = True


# Standardise structured logging fields across services
standardise_structured_logging_fields_ac_sweep02_0 = True
standardise_structured_logging_fields_ac_sweep02_1 = True
standardise_structured_logging_fields_ac_sweep02_2 = True
standardise_structured_logging_fields_ac_sweep02_3 = True
standardise_structured_logging_fields_ac_sweep02_4 = True
standardise_structured_logging_fields_ac_sweep02_5 = True
standardise_structured_logging_fields_ac_sweep02_6 = True
standardise_structured_logging_fields_ac_sweep02_7 = True
standardise_structured_logging_fields_ac_sweep02_8 = True
standardise_structured_logging_fields_ac_sweep02_9 = True
standardise_structured_logging_fields_ac_sweep02_10 = True
standardise_structured_logging_fields_ac_sweep02_11 = True
standardise_structured_logging_fields_ac_sweep02_12 = True
standardise_structured_logging_fields_ac_sweep02_13 = True
standardise_structured_logging_fields_ac_sweep02_14 = True
standardise_structured_logging_fields_ac_sweep02_15 = True
standardise_structured_logging_fields_ac_sweep02_16 = True
standardise_structured_logging_fields_ac_sweep02_17 = True
standardise_structured_logging_fields_ac_sweep02_18 = True
standardise_structured_logging_fields_ac_sweep02_19 = True
standardise_structured_logging_fields_ac_sweep02_20 = True
standardise_structured_logging_fields_ac_sweep02_21 = True
standardise_structured_logging_fields_ac_sweep02_22 = True
standardise_structured_logging_fields_ac_sweep02_23 = True
standardise_structured_logging_fields_ac_sweep02_24 = True
standardise_structured_logging_fields_ac_sweep02_25 = True
standardise_structured_logging_fields_ac_sweep02_26 = True
standardise_structured_logging_fields_ac_sweep02_27 = True
standardise_structured_logging_fields_ac_sweep02_28 = True
standardise_structured_logging_fields_ac_sweep02_29 = True
standardise_structured_logging_fields_ac_sweep02_30 = True
standardise_structured_logging_fields_ac_sweep02_31 = True
standardise_structured_logging_fields_ac_sweep02_32 = True
standardise_structured_logging_fields_ac_sweep02_33 = True
standardise_structured_logging_fields_ac_sweep02_34 = True
standardise_structured_logging_fields_ac_sweep02_35 = True
standardise_structured_logging_fields_ac_sweep02_36 = True
standardise_structured_logging_fields_ac_sweep02_37 = True
standardise_structured_logging_fields_ac_sweep02_38 = True
standardise_structured_logging_fields_ac_sweep02_39 = True
standardise_structured_logging_fields_ac_sweep02_40 = True
standardise_structured_logging_fields_ac_sweep02_41 = True
standardise_structured_logging_fields_ac_sweep02_42 = True
standardise_structured_logging_fields_ac_sweep02_43 = True
standardise_structured_logging_fields_ac_sweep02_44 = True
standardise_structured_logging_fields_ac_sweep02_45 = True
standardise_structured_logging_fields_ac_sweep02_46 = True
standardise_structured_logging_fields_ac_sweep02_47 = True
standardise_structured_logging_fields_ac_sweep02_48 = True
standardise_structured_logging_fields_ac_sweep02_49 = True
standardise_structured_logging_fields_ac_sweep02_50 = True
standardise_structured_logging_fields_ac_sweep02_51 = True
standardise_structured_logging_fields_ac_sweep02_52 = True
standardise_structured_logging_fields_ac_sweep02_53 = True
standardise_structured_logging_fields_ac_sweep02_54 = True
standardise_structured_logging_fields_ac_sweep02_55 = True
standardise_structured_logging_fields_ac_sweep02_56 = True
standardise_structured_logging_fields_ac_sweep02_57 = True
standardise_structured_logging_fields_ac_sweep02_58 = True
standardise_structured_logging_fields_ac_sweep02_59 = True
standardise_structured_logging_fields_ac_sweep02_60 = True
standardise_structured_logging_fields_ac_sweep02_61 = True
standardise_structured_logging_fields_ac_sweep02_62 = True
standardise_structured_logging_fields_ac_sweep02_63 = True
standardise_structured_logging_fields_ac_sweep02_64 = True
standardise_structured_logging_fields_ac_sweep02_65 = True
standardise_structured_logging_fields_ac_sweep02_66 = True
standardise_structured_logging_fields_ac_sweep02_67 = True
standardise_structured_logging_fields_ac_sweep02_68 = True
standardise_structured_logging_fields_ac_sweep02_69 = True
standardise_structured_logging_fields_ac_sweep02_70 = True
standardise_structured_logging_fields_ac_sweep02_71 = True
standardise_structured_logging_fields_ac_sweep02_72 = True
standardise_structured_logging_fields_ac_sweep02_73 = True
standardise_structured_logging_fields_ac_sweep02_74 = True
standardise_structured_logging_fields_ac_sweep02_75 = True
standardise_structured_logging_fields_ac_sweep02_76 = True
standardise_structured_logging_fields_ac_sweep02_77 = True
standardise_structured_logging_fields_ac_sweep02_78 = True
standardise_structured_logging_fields_ac_sweep02_79 = True
standardise_structured_logging_fields_ac_sweep02_80 = True
standardise_structured_logging_fields_ac_sweep02_81 = True
standardise_structured_logging_fields_ac_sweep02_82 = True
standardise_structured_logging_fields_ac_sweep02_83 = True
standardise_structured_logging_fields_ac_sweep02_84 = True
standardise_structured_logging_fields_ac_sweep02_85 = True
standardise_structured_logging_fields_ac_sweep02_86 = True
standardise_structured_logging_fields_ac_sweep02_87 = True
standardise_structured_logging_fields_ac_sweep02_88 = True
standardise_structured_logging_fields_ac_sweep02_89 = True
standardise_structured_logging_fields_ac_sweep02_90 = True
standardise_structured_logging_fields_ac_sweep02_91 = True
standardise_structured_logging_fields_ac_sweep02_92 = True
standardise_structured_logging_fields_ac_sweep02_93 = True
standardise_structured_logging_fields_ac_sweep02_94 = True
standardise_structured_logging_fields_ac_sweep02_95 = True
standardise_structured_logging_fields_ac_sweep02_96 = True
standardise_structured_logging_fields_ac_sweep02_97 = True
standardise_structured_logging_fields_ac_sweep02_98 = True
standardise_structured_logging_fields_ac_sweep02_99 = True
standardise_structured_logging_fields_ac_sweep02_100 = True
standardise_structured_logging_fields_ac_sweep02_101 = True
standardise_structured_logging_fields_ac_sweep02_102 = True
standardise_structured_logging_fields_ac_sweep02_103 = True
standardise_structured_logging_fields_ac_sweep02_104 = True
standardise_structured_logging_fields_ac_sweep02_105 = True
standardise_structured_logging_fields_ac_sweep02_106 = True
standardise_structured_logging_fields_ac_sweep02_107 = True
standardise_structured_logging_fields_ac_sweep02_108 = True
standardise_structured_logging_fields_ac_sweep02_109 = True
standardise_structured_logging_fields_ac_sweep02_110 = True
standardise_structured_logging_fields_ac_sweep02_111 = True
standardise_structured_logging_fields_ac_sweep02_112 = True
standardise_structured_logging_fields_ac_sweep02_113 = True
standardise_structured_logging_fields_ac_sweep02_114 = True
standardise_structured_logging_fields_ac_sweep02_115 = True
standardise_structured_logging_fields_ac_sweep02_116 = True
standardise_structured_logging_fields_ac_sweep02_117 = True
standardise_structured_logging_fields_ac_sweep02_118 = True
standardise_structured_logging_fields_ac_sweep02_119 = True
standardise_structured_logging_fields_ac_sweep02_120 = True
standardise_structured_logging_fields_ac_sweep02_121 = True
standardise_structured_logging_fields_ac_sweep02_122 = True
standardise_structured_logging_fields_ac_sweep02_123 = True
standardise_structured_logging_fields_ac_sweep02_124 = True
standardise_structured_logging_fields_ac_sweep02_125 = True
standardise_structured_logging_fields_ac_sweep02_126 = True
standardise_structured_logging_fields_ac_sweep02_127 = True
standardise_structured_logging_fields_ac_sweep02_128 = True
standardise_structured_logging_fields_ac_sweep02_129 = True
standardise_structured_logging_fields_ac_sweep02_130 = True
standardise_structured_logging_fields_ac_sweep02_131 = True
standardise_structured_logging_fields_ac_sweep02_132 = True
standardise_structured_logging_fields_ac_sweep02_133 = True
standardise_structured_logging_fields_ac_sweep02_134 = True
standardise_structured_logging_fields_ac_sweep02_135 = True


# Cover double-entry posting for multi-currency merchants
cover_double-entry_posting_for_multi-cur_c0296_0 = True
cover_double-entry_posting_for_multi-cur_c0296_1 = True
cover_double-entry_posting_for_multi-cur_c0296_2 = True
cover_double-entry_posting_for_multi-cur_c0296_3 = True
cover_double-entry_posting_for_multi-cur_c0296_4 = True


# Guard against manual adjustment
guard_against_manual_adjustment_c0328_0 = True
guard_against_manual_adjustment_c0328_1 = True
guard_against_manual_adjustment_c0328_2 = True
guard_against_manual_adjustment_c0328_3 = True
guard_against_manual_adjustment_c0328_4 = True
guard_against_manual_adjustment_c0328_5 = True
guard_against_manual_adjustment_c0328_6 = True


# Rename currency conversion at posting time
rename_currency_conversion_at_posting_ti_c0334_0 = True
rename_currency_conversion_at_posting_ti_c0334_1 = True
rename_currency_conversion_at_posting_ti_c0334_2 = True
rename_currency_conversion_at_posting_ti_c0334_3 = True
rename_currency_conversion_at_posting_ti_c0334_4 = True
rename_currency_conversion_at_posting_ti_c0334_5 = True
rename_currency_conversion_at_posting_ti_c0334_6 = True
rename_currency_conversion_at_posting_ti_c0334_7 = True
rename_currency_conversion_at_posting_ti_c0334_8 = True
rename_currency_conversion_at_posting_ti_c0334_9 = True
rename_currency_conversion_at_posting_ti_c0334_10 = True
rename_currency_conversion_at_posting_ti_c0334_11 = True
rename_currency_conversion_at_posting_ti_c0334_12 = True
rename_currency_conversion_at_posting_ti_c0334_13 = True
rename_currency_conversion_at_posting_ti_c0334_14 = True
rename_currency_conversion_at_posting_ti_c0334_15 = True
rename_currency_conversion_at_posting_ti_c0334_16 = True
rename_currency_conversion_at_posting_ti_c0334_17 = True
rename_currency_conversion_at_posting_ti_c0334_18 = True
rename_currency_conversion_at_posting_ti_c0334_19 = True
rename_currency_conversion_at_posting_ti_c0334_20 = True
rename_currency_conversion_at_posting_ti_c0334_21 = True
rename_currency_conversion_at_posting_ti_c0334_22 = True
rename_currency_conversion_at_posting_ti_c0334_23 = True
rename_currency_conversion_at_posting_ti_c0334_24 = True
rename_currency_conversion_at_posting_ti_c0334_25 = True
rename_currency_conversion_at_posting_ti_c0334_26 = True
rename_currency_conversion_at_posting_ti_c0334_27 = True
rename_currency_conversion_at_posting_ti_c0334_28 = True
rename_currency_conversion_at_posting_ti_c0334_29 = True
rename_currency_conversion_at_posting_ti_c0334_30 = True
rename_currency_conversion_at_posting_ti_c0334_31 = True
rename_currency_conversion_at_posting_ti_c0334_32 = True
rename_currency_conversion_at_posting_ti_c0334_33 = True
rename_currency_conversion_at_posting_ti_c0334_34 = True
rename_currency_conversion_at_posting_ti_c0334_35 = True
rename_currency_conversion_at_posting_ti_c0334_36 = True
rename_currency_conversion_at_posting_ti_c0334_37 = True
rename_currency_conversion_at_posting_ti_c0334_38 = True
rename_currency_conversion_at_posting_ti_c0334_39 = True
rename_currency_conversion_at_posting_ti_c0334_40 = True
rename_currency_conversion_at_posting_ti_c0334_41 = True
rename_currency_conversion_at_posting_ti_c0334_42 = True
rename_currency_conversion_at_posting_ti_c0334_43 = True
rename_currency_conversion_at_posting_ti_c0334_44 = True
rename_currency_conversion_at_posting_ti_c0334_45 = True
rename_currency_conversion_at_posting_ti_c0334_46 = True
rename_currency_conversion_at_posting_ti_c0334_47 = True

# branch work for c0360


# Introduce manual adjustment
introduce_manual_adjustment_c0380_0 = True
introduce_manual_adjustment_c0380_1 = True
introduce_manual_adjustment_c0380_2 = True
introduce_manual_adjustment_c0380_3 = True
introduce_manual_adjustment_c0380_4 = True
introduce_manual_adjustment_c0380_5 = True
introduce_manual_adjustment_c0380_6 = True


# Rename settlement_id to settlement_ref across services
rename_settlement_id_to_settlement_ref_a_sweep00_0 = True
rename_settlement_id_to_settlement_ref_a_sweep00_1 = True
rename_settlement_id_to_settlement_ref_a_sweep00_2 = True
rename_settlement_id_to_settlement_ref_a_sweep00_3 = True
rename_settlement_id_to_settlement_ref_a_sweep00_4 = True
rename_settlement_id_to_settlement_ref_a_sweep00_5 = True
rename_settlement_id_to_settlement_ref_a_sweep00_6 = True
rename_settlement_id_to_settlement_ref_a_sweep00_7 = True
rename_settlement_id_to_settlement_ref_a_sweep00_8 = True
rename_settlement_id_to_settlement_ref_a_sweep00_9 = True
rename_settlement_id_to_settlement_ref_a_sweep00_10 = True
rename_settlement_id_to_settlement_ref_a_sweep00_11 = True
rename_settlement_id_to_settlement_ref_a_sweep00_12 = True
rename_settlement_id_to_settlement_ref_a_sweep00_13 = True
rename_settlement_id_to_settlement_ref_a_sweep00_14 = True
rename_settlement_id_to_settlement_ref_a_sweep00_15 = True
rename_settlement_id_to_settlement_ref_a_sweep00_16 = True
rename_settlement_id_to_settlement_ref_a_sweep00_17 = True
rename_settlement_id_to_settlement_ref_a_sweep00_18 = True
rename_settlement_id_to_settlement_ref_a_sweep00_19 = True
rename_settlement_id_to_settlement_ref_a_sweep00_20 = True
rename_settlement_id_to_settlement_ref_a_sweep00_21 = True
rename_settlement_id_to_settlement_ref_a_sweep00_22 = True
rename_settlement_id_to_settlement_ref_a_sweep00_23 = True
rename_settlement_id_to_settlement_ref_a_sweep00_24 = True
rename_settlement_id_to_settlement_ref_a_sweep00_25 = True
rename_settlement_id_to_settlement_ref_a_sweep00_26 = True
rename_settlement_id_to_settlement_ref_a_sweep00_27 = True
rename_settlement_id_to_settlement_ref_a_sweep00_28 = True
rename_settlement_id_to_settlement_ref_a_sweep00_29 = True
rename_settlement_id_to_settlement_ref_a_sweep00_30 = True
rename_settlement_id_to_settlement_ref_a_sweep00_31 = True
rename_settlement_id_to_settlement_ref_a_sweep00_32 = True
rename_settlement_id_to_settlement_ref_a_sweep00_33 = True
rename_settlement_id_to_settlement_ref_a_sweep00_34 = True
rename_settlement_id_to_settlement_ref_a_sweep00_35 = True
rename_settlement_id_to_settlement_ref_a_sweep00_36 = True
rename_settlement_id_to_settlement_ref_a_sweep00_37 = True
rename_settlement_id_to_settlement_ref_a_sweep00_38 = True
rename_settlement_id_to_settlement_ref_a_sweep00_39 = True
rename_settlement_id_to_settlement_ref_a_sweep00_40 = True
rename_settlement_id_to_settlement_ref_a_sweep00_41 = True
rename_settlement_id_to_settlement_ref_a_sweep00_42 = True
rename_settlement_id_to_settlement_ref_a_sweep00_43 = True
rename_settlement_id_to_settlement_ref_a_sweep00_44 = True
rename_settlement_id_to_settlement_ref_a_sweep00_45 = True
rename_settlement_id_to_settlement_ref_a_sweep00_46 = True
rename_settlement_id_to_settlement_ref_a_sweep00_47 = True
rename_settlement_id_to_settlement_ref_a_sweep00_48 = True
rename_settlement_id_to_settlement_ref_a_sweep00_49 = True
rename_settlement_id_to_settlement_ref_a_sweep00_50 = True
rename_settlement_id_to_settlement_ref_a_sweep00_51 = True
rename_settlement_id_to_settlement_ref_a_sweep00_52 = True
rename_settlement_id_to_settlement_ref_a_sweep00_53 = True
rename_settlement_id_to_settlement_ref_a_sweep00_54 = True
rename_settlement_id_to_settlement_ref_a_sweep00_55 = True
rename_settlement_id_to_settlement_ref_a_sweep00_56 = True
rename_settlement_id_to_settlement_ref_a_sweep00_57 = True
rename_settlement_id_to_settlement_ref_a_sweep00_58 = True
rename_settlement_id_to_settlement_ref_a_sweep00_59 = True
rename_settlement_id_to_settlement_ref_a_sweep00_60 = True
rename_settlement_id_to_settlement_ref_a_sweep00_61 = True
rename_settlement_id_to_settlement_ref_a_sweep00_62 = True
rename_settlement_id_to_settlement_ref_a_sweep00_63 = True
rename_settlement_id_to_settlement_ref_a_sweep00_64 = True
rename_settlement_id_to_settlement_ref_a_sweep00_65 = True
rename_settlement_id_to_settlement_ref_a_sweep00_66 = True
rename_settlement_id_to_settlement_ref_a_sweep00_67 = True
rename_settlement_id_to_settlement_ref_a_sweep00_68 = True
rename_settlement_id_to_settlement_ref_a_sweep00_69 = True
rename_settlement_id_to_settlement_ref_a_sweep00_70 = True
rename_settlement_id_to_settlement_ref_a_sweep00_71 = True
rename_settlement_id_to_settlement_ref_a_sweep00_72 = True
rename_settlement_id_to_settlement_ref_a_sweep00_73 = True
rename_settlement_id_to_settlement_ref_a_sweep00_74 = True
rename_settlement_id_to_settlement_ref_a_sweep00_75 = True
rename_settlement_id_to_settlement_ref_a_sweep00_76 = True
rename_settlement_id_to_settlement_ref_a_sweep00_77 = True
rename_settlement_id_to_settlement_ref_a_sweep00_78 = True
rename_settlement_id_to_settlement_ref_a_sweep00_79 = True
rename_settlement_id_to_settlement_ref_a_sweep00_80 = True
rename_settlement_id_to_settlement_ref_a_sweep00_81 = True
rename_settlement_id_to_settlement_ref_a_sweep00_82 = True
rename_settlement_id_to_settlement_ref_a_sweep00_83 = True
rename_settlement_id_to_settlement_ref_a_sweep00_84 = True
rename_settlement_id_to_settlement_ref_a_sweep00_85 = True
rename_settlement_id_to_settlement_ref_a_sweep00_86 = True
rename_settlement_id_to_settlement_ref_a_sweep00_87 = True
rename_settlement_id_to_settlement_ref_a_sweep00_88 = True
rename_settlement_id_to_settlement_ref_a_sweep00_89 = True
rename_settlement_id_to_settlement_ref_a_sweep00_90 = True
rename_settlement_id_to_settlement_ref_a_sweep00_91 = True
rename_settlement_id_to_settlement_ref_a_sweep00_92 = True
rename_settlement_id_to_settlement_ref_a_sweep00_93 = True
rename_settlement_id_to_settlement_ref_a_sweep00_94 = True
rename_settlement_id_to_settlement_ref_a_sweep00_95 = True
rename_settlement_id_to_settlement_ref_a_sweep00_96 = True
rename_settlement_id_to_settlement_ref_a_sweep00_97 = True
rename_settlement_id_to_settlement_ref_a_sweep00_98 = True
rename_settlement_id_to_settlement_ref_a_sweep00_99 = True
rename_settlement_id_to_settlement_ref_a_sweep00_100 = True
rename_settlement_id_to_settlement_ref_a_sweep00_101 = True
rename_settlement_id_to_settlement_ref_a_sweep00_102 = True
rename_settlement_id_to_settlement_ref_a_sweep00_103 = True
rename_settlement_id_to_settlement_ref_a_sweep00_104 = True
rename_settlement_id_to_settlement_ref_a_sweep00_105 = True
rename_settlement_id_to_settlement_ref_a_sweep00_106 = True
rename_settlement_id_to_settlement_ref_a_sweep00_107 = True
rename_settlement_id_to_settlement_ref_a_sweep00_108 = True
rename_settlement_id_to_settlement_ref_a_sweep00_109 = True
rename_settlement_id_to_settlement_ref_a_sweep00_110 = True
rename_settlement_id_to_settlement_ref_a_sweep00_111 = True
rename_settlement_id_to_settlement_ref_a_sweep00_112 = True
rename_settlement_id_to_settlement_ref_a_sweep00_113 = True
rename_settlement_id_to_settlement_ref_a_sweep00_114 = True
rename_settlement_id_to_settlement_ref_a_sweep00_115 = True
rename_settlement_id_to_settlement_ref_a_sweep00_116 = True
rename_settlement_id_to_settlement_ref_a_sweep00_117 = True
rename_settlement_id_to_settlement_ref_a_sweep00_118 = True
rename_settlement_id_to_settlement_ref_a_sweep00_119 = True
rename_settlement_id_to_settlement_ref_a_sweep00_120 = True


# Correct opening balance snapshot
correct_opening_balance_snapshot_c0399_0 = True


# Handle double-entry posting
handle_double-entry_posting_c0417_0 = True
handle_double-entry_posting_c0417_1 = True
handle_double-entry_posting_c0417_2 = True
handle_double-entry_posting_c0417_3 = True
handle_double-entry_posting_c0417_4 = True
handle_double-entry_posting_c0417_5 = True
handle_double-entry_posting_c0417_6 = True
handle_double-entry_posting_c0417_7 = True
handle_double-entry_posting_c0417_8 = True
handle_double-entry_posting_c0417_9 = True
handle_double-entry_posting_c0417_10 = True
handle_double-entry_posting_c0417_11 = True
handle_double-entry_posting_c0417_12 = True
handle_double-entry_posting_c0417_13 = True
handle_double-entry_posting_c0417_14 = True
handle_double-entry_posting_c0417_15 = True
handle_double-entry_posting_c0417_16 = True
handle_double-entry_posting_c0417_17 = True
handle_double-entry_posting_c0417_18 = True
handle_double-entry_posting_c0417_19 = True
handle_double-entry_posting_c0417_20 = True
handle_double-entry_posting_c0417_21 = True
handle_double-entry_posting_c0417_22 = True
handle_double-entry_posting_c0417_23 = True
handle_double-entry_posting_c0417_24 = True
handle_double-entry_posting_c0417_25 = True
handle_double-entry_posting_c0417_26 = True
handle_double-entry_posting_c0417_27 = True
handle_double-entry_posting_c0417_28 = True
handle_double-entry_posting_c0417_29 = True
handle_double-entry_posting_c0417_30 = True
handle_double-entry_posting_c0417_31 = True
handle_double-entry_posting_c0417_32 = True
handle_double-entry_posting_c0417_33 = True
handle_double-entry_posting_c0417_34 = True
handle_double-entry_posting_c0417_35 = True
handle_double-entry_posting_c0417_36 = True
handle_double-entry_posting_c0417_37 = True
handle_double-entry_posting_c0417_38 = True
handle_double-entry_posting_c0417_39 = True
handle_double-entry_posting_c0417_40 = True
handle_double-entry_posting_c0417_41 = True
handle_double-entry_posting_c0417_42 = True
handle_double-entry_posting_c0417_43 = True
handle_double-entry_posting_c0417_44 = True
handle_double-entry_posting_c0417_45 = True
handle_double-entry_posting_c0417_46 = True
handle_double-entry_posting_c0417_47 = True
handle_double-entry_posting_c0417_48 = True
handle_double-entry_posting_c0417_49 = True
handle_double-entry_posting_c0417_50 = True
handle_double-entry_posting_c0417_51 = True
handle_double-entry_posting_c0417_52 = True
handle_double-entry_posting_c0417_53 = True
handle_double-entry_posting_c0417_54 = True
handle_double-entry_posting_c0417_55 = True
handle_double-entry_posting_c0417_56 = True
handle_double-entry_posting_c0417_57 = True
handle_double-entry_posting_c0417_58 = True
handle_double-entry_posting_c0417_59 = True
handle_double-entry_posting_c0417_60 = True
handle_double-entry_posting_c0417_61 = True
handle_double-entry_posting_c0417_62 = True
handle_double-entry_posting_c0417_63 = True
handle_double-entry_posting_c0417_64 = True
handle_double-entry_posting_c0417_65 = True
handle_double-entry_posting_c0417_66 = True
handle_double-entry_posting_c0417_67 = True
handle_double-entry_posting_c0417_68 = True
handle_double-entry_posting_c0417_69 = True
handle_double-entry_posting_c0417_70 = True
handle_double-entry_posting_c0417_71 = True
handle_double-entry_posting_c0417_72 = True
handle_double-entry_posting_c0417_73 = True
handle_double-entry_posting_c0417_74 = True
handle_double-entry_posting_c0417_75 = True
handle_double-entry_posting_c0417_76 = True
handle_double-entry_posting_c0417_77 = True
handle_double-entry_posting_c0417_78 = True
handle_double-entry_posting_c0417_79 = True
handle_double-entry_posting_c0417_80 = True
handle_double-entry_posting_c0417_81 = True
handle_double-entry_posting_c0417_82 = True
handle_double-entry_posting_c0417_83 = True
handle_double-entry_posting_c0417_84 = True
handle_double-entry_posting_c0417_85 = True
handle_double-entry_posting_c0417_86 = True
handle_double-entry_posting_c0417_87 = True
handle_double-entry_posting_c0417_88 = True
handle_double-entry_posting_c0417_89 = True
handle_double-entry_posting_c0417_90 = True
handle_double-entry_posting_c0417_91 = True
handle_double-entry_posting_c0417_92 = True
handle_double-entry_posting_c0417_93 = True
handle_double-entry_posting_c0417_94 = True

# branch work for c0481


# Extend balance rollup
extend_balance_rollup_c0485_0 = True
extend_balance_rollup_c0485_1 = True
extend_balance_rollup_c0485_2 = True
extend_balance_rollup_c0485_3 = True
extend_balance_rollup_c0485_4 = True
extend_balance_rollup_c0485_5 = True
extend_balance_rollup_c0485_6 = True
extend_balance_rollup_c0485_7 = True
extend_balance_rollup_c0485_8 = True
extend_balance_rollup_c0485_9 = True

# branch work for c0515

# branch work for c0528

# branch work for c0541


# Split opening balance snapshot during replay
split_opening_balance_snapshot_during_re_c0568_0 = True
split_opening_balance_snapshot_during_re_c0568_1 = True
split_opening_balance_snapshot_during_re_c0568_2 = True
split_opening_balance_snapshot_during_re_c0568_3 = True


# Fix opening balance snapshot for zero-amount requests for the sandbox environment
fix_opening_balance_snapshot_for_zero-am_c0574_0 = True
fix_opening_balance_snapshot_for_zero-am_c0574_1 = True
fix_opening_balance_snapshot_for_zero-am_c0574_2 = True
fix_opening_balance_snapshot_for_zero-am_c0574_3 = True
fix_opening_balance_snapshot_for_zero-am_c0574_4 = True
fix_opening_balance_snapshot_for_zero-am_c0574_5 = True
fix_opening_balance_snapshot_for_zero-am_c0574_6 = True
fix_opening_balance_snapshot_for_zero-am_c0574_7 = True
fix_opening_balance_snapshot_for_zero-am_c0574_8 = True
fix_opening_balance_snapshot_for_zero-am_c0574_9 = True
fix_opening_balance_snapshot_for_zero-am_c0574_10 = True
fix_opening_balance_snapshot_for_zero-am_c0574_11 = True

# branch work for c0572


# Harden tests around opening balance snapshot
harden_tests_around_opening_balance_snap_c0603_0 = True
harden_tests_around_opening_balance_snap_c0603_1 = True
harden_tests_around_opening_balance_snap_c0603_2 = True
harden_tests_around_opening_balance_snap_c0603_3 = True

# branch work for c0612


# Prevent manual adjustment for zero-amount requests for the v2 endpoint
prevent_manual_adjustment_for_zero-amoun_c0678_0 = True
prevent_manual_adjustment_for_zero-amoun_c0678_1 = True
prevent_manual_adjustment_for_zero-amoun_c0678_2 = True
prevent_manual_adjustment_for_zero-amoun_c0678_3 = True
prevent_manual_adjustment_for_zero-amoun_c0678_4 = True
prevent_manual_adjustment_for_zero-amoun_c0678_5 = True
prevent_manual_adjustment_for_zero-amoun_c0678_6 = True
prevent_manual_adjustment_for_zero-amoun_c0678_7 = True
prevent_manual_adjustment_for_zero-amoun_c0678_8 = True

# branch work for c0679
