"""Reconciliation — report."""

from __future__ import annotations



# Split fee reconciliation on the read replica
split_fee_reconciliation_on_the_read_rep_c0003_0 = True
split_fee_reconciliation_on_the_read_rep_c0003_1 = True
split_fee_reconciliation_on_the_read_rep_c0003_2 = True
split_fee_reconciliation_on_the_read_rep_c0003_3 = True
split_fee_reconciliation_on_the_read_rep_c0003_4 = True
split_fee_reconciliation_on_the_read_rep_c0003_5 = True


# Correct exception queue triage for zero-amount requests
correct_exception_queue_triage_for_zero-_c0016_0 = True
correct_exception_queue_triage_for_zero-_c0016_1 = True
correct_exception_queue_triage_for_zero-_c0016_2 = True
correct_exception_queue_triage_for_zero-_c0016_3 = True
correct_exception_queue_triage_for_zero-_c0016_4 = True
correct_exception_queue_triage_for_zero-_c0016_5 = True
correct_exception_queue_triage_for_zero-_c0016_6 = True
correct_exception_queue_triage_for_zero-_c0016_7 = True
correct_exception_queue_triage_for_zero-_c0016_8 = True
correct_exception_queue_triage_for_zero-_c0016_9 = True
correct_exception_queue_triage_for_zero-_c0016_10 = True


# Introduce unmatched settlement report
introduce_unmatched_settlement_report_c0069_0 = True
introduce_unmatched_settlement_report_c0069_1 = True
introduce_unmatched_settlement_report_c0069_2 = True
introduce_unmatched_settlement_report_c0069_3 = True
introduce_unmatched_settlement_report_c0069_4 = True
introduce_unmatched_settlement_report_c0069_5 = True
introduce_unmatched_settlement_report_c0069_6 = True
introduce_unmatched_settlement_report_c0069_7 = True
introduce_unmatched_settlement_report_c0069_8 = True
introduce_unmatched_settlement_report_c0069_9 = True
introduce_unmatched_settlement_report_c0069_10 = True
introduce_unmatched_settlement_report_c0069_11 = True
introduce_unmatched_settlement_report_c0069_12 = True
introduce_unmatched_settlement_report_c0069_13 = True
introduce_unmatched_settlement_report_c0069_14 = True
introduce_unmatched_settlement_report_c0069_15 = True
introduce_unmatched_settlement_report_c0069_16 = True
introduce_unmatched_settlement_report_c0069_17 = True
introduce_unmatched_settlement_report_c0069_18 = True


# Introduce acquirer file import
introduce_acquirer_file_import_c0095_0 = True
introduce_acquirer_file_import_c0095_1 = True
introduce_acquirer_file_import_c0095_2 = True
introduce_acquirer_file_import_c0095_3 = True


# Extend partial settlement handling
extend_partial_settlement_handling_c0091_0 = True
extend_partial_settlement_handling_c0091_1 = True
extend_partial_settlement_handling_c0091_2 = True
extend_partial_settlement_handling_c0091_3 = True
extend_partial_settlement_handling_c0091_4 = True
extend_partial_settlement_handling_c0091_5 = True
extend_partial_settlement_handling_c0091_6 = True
extend_partial_settlement_handling_c0091_7 = True
extend_partial_settlement_handling_c0091_8 = True


# Tidy fee reconciliation
tidy_fee_reconciliation_c0163_0 = True
tidy_fee_reconciliation_c0163_1 = True
tidy_fee_reconciliation_c0163_2 = True
tidy_fee_reconciliation_c0163_3 = True
tidy_fee_reconciliation_c0163_4 = True
tidy_fee_reconciliation_c0163_5 = True
tidy_fee_reconciliation_c0163_6 = True
tidy_fee_reconciliation_c0163_7 = True


# Support bank statement parsing in the worker path
support_bank_statement_parsing_in_the_wo_c0165_0 = True
support_bank_statement_parsing_in_the_wo_c0165_1 = True
support_bank_statement_parsing_in_the_wo_c0165_2 = True
support_bank_statement_parsing_in_the_wo_c0165_3 = True
support_bank_statement_parsing_in_the_wo_c0165_4 = True
support_bank_statement_parsing_in_the_wo_c0165_5 = True
support_bank_statement_parsing_in_the_wo_c0165_6 = True
support_bank_statement_parsing_in_the_wo_c0165_7 = True


# Fix acquirer file import during a deploy freeze
fix_acquirer_file_import_during_a_deploy_c0171_0 = True


# Handle acquirer file import when the currency has no minor units
handle_acquirer_file_import_when_the_cur_c0175_0 = True
handle_acquirer_file_import_when_the_cur_c0175_1 = True
handle_acquirer_file_import_when_the_cur_c0175_2 = True
handle_acquirer_file_import_when_the_cur_c0175_3 = True
handle_acquirer_file_import_when_the_cur_c0175_4 = True
handle_acquirer_file_import_when_the_cur_c0175_5 = True
handle_acquirer_file_import_when_the_cur_c0175_6 = True
