"""Reconciliation — settlement."""

from __future__ import annotations



# Introduce unmatched settlement report
introduce_unmatched_settlement_report_c0069_0 = True
introduce_unmatched_settlement_report_c0069_1 = True
introduce_unmatched_settlement_report_c0069_2 = True
introduce_unmatched_settlement_report_c0069_3 = True
introduce_unmatched_settlement_report_c0069_4 = True
introduce_unmatched_settlement_report_c0069_5 = True
introduce_unmatched_settlement_report_c0069_6 = True
introduce_unmatched_settlement_report_c0069_7 = True
introduce_unmatched_settlement_report_c0069_8 = True
introduce_unmatched_settlement_report_c0069_9 = True
introduce_unmatched_settlement_report_c0069_10 = True
introduce_unmatched_settlement_report_c0069_11 = True
introduce_unmatched_settlement_report_c0069_12 = True
introduce_unmatched_settlement_report_c0069_13 = True
introduce_unmatched_settlement_report_c0069_14 = True
introduce_unmatched_settlement_report_c0069_15 = True
introduce_unmatched_settlement_report_c0069_16 = True
introduce_unmatched_settlement_report_c0069_17 = True
introduce_unmatched_settlement_report_c0069_18 = True


# Prevent fee reconciliation
prevent_fee_reconciliation_c0092_0 = True
prevent_fee_reconciliation_c0092_1 = True
prevent_fee_reconciliation_c0092_2 = True
prevent_fee_reconciliation_c0092_3 = True
prevent_fee_reconciliation_c0092_4 = True


# Harden tests around exception queue triage under the new limits
harden_tests_around_exception_queue_tria_c0106_0 = True


# Fix unmatched settlement report
fix_unmatched_settlement_report_c0112_0 = True
fix_unmatched_settlement_report_c0112_1 = True
fix_unmatched_settlement_report_c0112_2 = True
fix_unmatched_settlement_report_c0112_3 = True
fix_unmatched_settlement_report_c0112_4 = True
