"""Payments API — retry."""

from __future__ import annotations



# Extend partial capture handling during replay
extend_partial_capture_handling_during_r_c0116_0 = True
extend_partial_capture_handling_during_r_c0116_1 = True
extend_partial_capture_handling_during_r_c0116_2 = True
extend_partial_capture_handling_during_r_c0116_3 = True
extend_partial_capture_handling_during_r_c0116_4 = True
extend_partial_capture_handling_during_r_c0116_5 = True
extend_partial_capture_handling_during_r_c0116_6 = True
extend_partial_capture_handling_during_r_c0116_7 = True
extend_partial_capture_handling_during_r_c0116_8 = True
extend_partial_capture_handling_during_r_c0116_9 = True
extend_partial_capture_handling_during_r_c0116_10 = True
extend_partial_capture_handling_during_r_c0116_11 = True
extend_partial_capture_handling_during_r_c0116_12 = True
extend_partial_capture_handling_during_r_c0116_13 = True
extend_partial_capture_handling_during_r_c0116_14 = True
extend_partial_capture_handling_during_r_c0116_15 = True
extend_partial_capture_handling_during_r_c0116_16 = True


# Rename refund flow
rename_refund_flow_c0170_0 = True
rename_refund_flow_c0170_1 = True


# Support error envelope during replay
support_error_envelope_during_replay_c0176_0 = True
support_error_envelope_during_replay_c0176_1 = True
support_error_envelope_during_replay_c0176_2 = True
support_error_envelope_during_replay_c0176_3 = True
support_error_envelope_during_replay_c0176_4 = True
support_error_envelope_during_replay_c0176_5 = True
support_error_envelope_during_replay_c0176_6 = True
support_error_envelope_during_replay_c0176_7 = True
support_error_envelope_during_replay_c0176_8 = True
support_error_envelope_during_replay_c0176_9 = True
support_error_envelope_during_replay_c0176_10 = True
support_error_envelope_during_replay_c0176_11 = True
support_error_envelope_during_replay_c0176_12 = True
support_error_envelope_during_replay_c0176_13 = True


# Split request validation
split_request_validation_c0203_0 = True
split_request_validation_c0203_1 = True
split_request_validation_c0203_2 = True
split_request_validation_c0203_3 = True
split_request_validation_c0203_4 = True
split_request_validation_c0203_5 = True
