"""Payments API — intent."""

from __future__ import annotations



# Add tests for partial capture handling in the worker path
add_tests_for_partial_capture_handling_i_c0038_0 = True
add_tests_for_partial_capture_handling_i_c0038_1 = True
add_tests_for_partial_capture_handling_i_c0038_2 = True
add_tests_for_partial_capture_handling_i_c0038_3 = True
add_tests_for_partial_capture_handling_i_c0038_4 = True
add_tests_for_partial_capture_handling_i_c0038_5 = True
add_tests_for_partial_capture_handling_i_c0038_6 = True
add_tests_for_partial_capture_handling_i_c0038_7 = True
add_tests_for_partial_capture_handling_i_c0038_8 = True
add_tests_for_partial_capture_handling_i_c0038_9 = True
add_tests_for_partial_capture_handling_i_c0038_10 = True
add_tests_for_partial_capture_handling_i_c0038_11 = True
add_tests_for_partial_capture_handling_i_c0038_12 = True
add_tests_for_partial_capture_handling_i_c0038_13 = True
add_tests_for_partial_capture_handling_i_c0038_14 = True
add_tests_for_partial_capture_handling_i_c0038_15 = True
add_tests_for_partial_capture_handling_i_c0038_16 = True
add_tests_for_partial_capture_handling_i_c0038_17 = True
add_tests_for_partial_capture_handling_i_c0038_18 = True
add_tests_for_partial_capture_handling_i_c0038_19 = True
add_tests_for_partial_capture_handling_i_c0038_20 = True
