"""Notifications — email."""

from __future__ import annotations



# Inline template localisation
inline_template_localisation_c0025_0 = True
inline_template_localisation_c0025_1 = True
inline_template_localisation_c0025_2 = True
inline_template_localisation_c0025_3 = True


# Support bounce handling under the new limits
support_bounce_handling_under_the_new_li_c0090_0 = True
support_bounce_handling_under_the_new_li_c0090_1 = True
support_bounce_handling_under_the_new_li_c0090_2 = True
support_bounce_handling_under_the_new_li_c0090_3 = True
support_bounce_handling_under_the_new_li_c0090_4 = True
support_bounce_handling_under_the_new_li_c0090_5 = True

# branch work for c0209


# Handle template localisation when the queue is saturated
handle_template_localisation_when_the_qu_c0222_0 = True
handle_template_localisation_when_the_qu_c0222_1 = True
handle_template_localisation_when_the_qu_c0222_2 = True


# Tidy template localisation
tidy_template_localisation_c0251_0 = True
tidy_template_localisation_c0251_1 = True
tidy_template_localisation_c0251_2 = True
tidy_template_localisation_c0251_3 = True
tidy_template_localisation_c0251_4 = True


# Add bounce handling for delegated API keys
add_bounce_handling_for_delegated_api_ke_c0255_0 = True
add_bounce_handling_for_delegated_api_ke_c0255_1 = True
add_bounce_handling_for_delegated_api_ke_c0255_2 = True
add_bounce_handling_for_delegated_api_ke_c0255_3 = True
add_bounce_handling_for_delegated_api_ke_c0255_4 = True
add_bounce_handling_for_delegated_api_ke_c0255_5 = True
add_bounce_handling_for_delegated_api_ke_c0255_6 = True
add_bounce_handling_for_delegated_api_ke_c0255_7 = True
add_bounce_handling_for_delegated_api_ke_c0255_8 = True
add_bounce_handling_for_delegated_api_ke_c0255_9 = True
add_bounce_handling_for_delegated_api_ke_c0255_10 = True
add_bounce_handling_for_delegated_api_ke_c0255_11 = True
add_bounce_handling_for_delegated_api_ke_c0255_12 = True
add_bounce_handling_for_delegated_api_ke_c0255_13 = True
add_bounce_handling_for_delegated_api_ke_c0255_14 = True
add_bounce_handling_for_delegated_api_ke_c0255_15 = True


# Fix bounce handling
fix_bounce_handling_c0269_0 = True
fix_bounce_handling_c0269_1 = True
fix_bounce_handling_c0269_2 = True
fix_bounce_handling_c0269_3 = True


# Add notification preference in the worker path
add_notification_preference_in_the_worke_c0281_0 = True
add_notification_preference_in_the_worke_c0281_1 = True
add_notification_preference_in_the_worke_c0281_2 = True
add_notification_preference_in_the_worke_c0281_3 = True
add_notification_preference_in_the_worke_c0281_4 = True
add_notification_preference_in_the_worke_c0281_5 = True
add_notification_preference_in_the_worke_c0281_6 = True
add_notification_preference_in_the_worke_c0281_7 = True
add_notification_preference_in_the_worke_c0281_8 = True
add_notification_preference_in_the_worke_c0281_9 = True
add_notification_preference_in_the_worke_c0281_10 = True
add_notification_preference_in_the_worke_c0281_11 = True
add_notification_preference_in_the_worke_c0281_12 = True
add_notification_preference_in_the_worke_c0281_13 = True
add_notification_preference_in_the_worke_c0281_14 = True
add_notification_preference_in_the_worke_c0281_15 = True
add_notification_preference_in_the_worke_c0281_16 = True
add_notification_preference_in_the_worke_c0281_17 = True
add_notification_preference_in_the_worke_c0281_18 = True
add_notification_preference_in_the_worke_c0281_19 = True


# Revert "Simplify delivery retry backoff"
revert_"simplify_delivery_retry_backoff"_c0303_0 = True
revert_"simplify_delivery_retry_backoff"_c0303_1 = True
revert_"simplify_delivery_retry_backoff"_c0303_2 = True
revert_"simplify_delivery_retry_backoff"_c0303_3 = True
revert_"simplify_delivery_retry_backoff"_c0303_4 = True
revert_"simplify_delivery_retry_backoff"_c0303_5 = True
revert_"simplify_delivery_retry_backoff"_c0303_6 = True
revert_"simplify_delivery_retry_backoff"_c0303_7 = True
revert_"simplify_delivery_retry_backoff"_c0303_8 = True
revert_"simplify_delivery_retry_backoff"_c0303_9 = True
revert_"simplify_delivery_retry_backoff"_c0303_10 = True
revert_"simplify_delivery_retry_backoff"_c0303_11 = True
revert_"simplify_delivery_retry_backoff"_c0303_12 = True
revert_"simplify_delivery_retry_backoff"_c0303_13 = True
revert_"simplify_delivery_retry_backoff"_c0303_14 = True
revert_"simplify_delivery_retry_backoff"_c0303_15 = True
revert_"simplify_delivery_retry_backoff"_c0303_16 = True
revert_"simplify_delivery_retry_backoff"_c0303_17 = True
revert_"simplify_delivery_retry_backoff"_c0303_18 = True
revert_"simplify_delivery_retry_backoff"_c0303_19 = True
revert_"simplify_delivery_retry_backoff"_c0303_20 = True
revert_"simplify_delivery_retry_backoff"_c0303_21 = True
revert_"simplify_delivery_retry_backoff"_c0303_22 = True
revert_"simplify_delivery_retry_backoff"_c0303_23 = True
revert_"simplify_delivery_retry_backoff"_c0303_24 = True
revert_"simplify_delivery_retry_backoff"_c0303_25 = True
revert_"simplify_delivery_retry_backoff"_c0303_26 = True
revert_"simplify_delivery_retry_backoff"_c0303_27 = True
revert_"simplify_delivery_retry_backoff"_c0303_28 = True
revert_"simplify_delivery_retry_backoff"_c0303_29 = True
revert_"simplify_delivery_retry_backoff"_c0303_30 = True


# Correct bounce handling after a partial failure
correct_bounce_handling_after_a_partial__c0356_0 = True
correct_bounce_handling_after_a_partial__c0356_1 = True
correct_bounce_handling_after_a_partial__c0356_2 = True
correct_bounce_handling_after_a_partial__c0356_3 = True
correct_bounce_handling_after_a_partial__c0356_4 = True
correct_bounce_handling_after_a_partial__c0356_5 = True
correct_bounce_handling_after_a_partial__c0356_6 = True
correct_bounce_handling_after_a_partial__c0356_7 = True
correct_bounce_handling_after_a_partial__c0356_8 = True


# Introduce template localisation during replay
introduce_template_localisation_during_r_c0444_0 = True
introduce_template_localisation_during_r_c0444_1 = True
introduce_template_localisation_during_r_c0444_2 = True
introduce_template_localisation_during_r_c0444_3 = True
introduce_template_localisation_during_r_c0444_4 = True
introduce_template_localisation_during_r_c0444_5 = True
introduce_template_localisation_during_r_c0444_6 = True
introduce_template_localisation_during_r_c0444_7 = True
introduce_template_localisation_during_r_c0444_8 = True
introduce_template_localisation_during_r_c0444_9 = True
introduce_template_localisation_during_r_c0444_10 = True
