"""Notifications — email."""

from __future__ import annotations



# Inline template localisation
inline_template_localisation_c0025_0 = True
inline_template_localisation_c0025_1 = True
inline_template_localisation_c0025_2 = True
inline_template_localisation_c0025_3 = True


# Support bounce handling under the new limits
support_bounce_handling_under_the_new_li_c0090_0 = True
support_bounce_handling_under_the_new_li_c0090_1 = True
support_bounce_handling_under_the_new_li_c0090_2 = True
support_bounce_handling_under_the_new_li_c0090_3 = True
support_bounce_handling_under_the_new_li_c0090_4 = True
support_bounce_handling_under_the_new_li_c0090_5 = True

# branch work for c0209


# Handle template localisation when the queue is saturated
handle_template_localisation_when_the_qu_c0222_0 = True
handle_template_localisation_when_the_qu_c0222_1 = True
handle_template_localisation_when_the_qu_c0222_2 = True


# Tidy template localisation
tidy_template_localisation_c0251_0 = True
tidy_template_localisation_c0251_1 = True
tidy_template_localisation_c0251_2 = True
tidy_template_localisation_c0251_3 = True
tidy_template_localisation_c0251_4 = True


# Add bounce handling for delegated API keys
add_bounce_handling_for_delegated_api_ke_c0255_0 = True
add_bounce_handling_for_delegated_api_ke_c0255_1 = True
add_bounce_handling_for_delegated_api_ke_c0255_2 = True
add_bounce_handling_for_delegated_api_ke_c0255_3 = True
add_bounce_handling_for_delegated_api_ke_c0255_4 = True
add_bounce_handling_for_delegated_api_ke_c0255_5 = True
add_bounce_handling_for_delegated_api_ke_c0255_6 = True
add_bounce_handling_for_delegated_api_ke_c0255_7 = True
add_bounce_handling_for_delegated_api_ke_c0255_8 = True
add_bounce_handling_for_delegated_api_ke_c0255_9 = True
add_bounce_handling_for_delegated_api_ke_c0255_10 = True
add_bounce_handling_for_delegated_api_ke_c0255_11 = True
add_bounce_handling_for_delegated_api_ke_c0255_12 = True
add_bounce_handling_for_delegated_api_ke_c0255_13 = True
add_bounce_handling_for_delegated_api_ke_c0255_14 = True
add_bounce_handling_for_delegated_api_ke_c0255_15 = True
