"""Payments API — captures."""

from __future__ import annotations



# Support intent expiry sweep
support_intent_expiry_sweep_c0026_0 = True
support_intent_expiry_sweep_c0026_1 = True
support_intent_expiry_sweep_c0026_2 = True
support_intent_expiry_sweep_c0026_3 = True
support_intent_expiry_sweep_c0026_4 = True
support_intent_expiry_sweep_c0026_5 = True
support_intent_expiry_sweep_c0026_6 = True
support_intent_expiry_sweep_c0026_7 = True
support_intent_expiry_sweep_c0026_8 = True
support_intent_expiry_sweep_c0026_9 = True
support_intent_expiry_sweep_c0026_10 = True
support_intent_expiry_sweep_c0026_11 = True
support_intent_expiry_sweep_c0026_12 = True
support_intent_expiry_sweep_c0026_13 = True
support_intent_expiry_sweep_c0026_14 = True
support_intent_expiry_sweep_c0026_15 = True
support_intent_expiry_sweep_c0026_16 = True
support_intent_expiry_sweep_c0026_17 = True
support_intent_expiry_sweep_c0026_18 = True


# Add tests for partial capture handling in the worker path
add_tests_for_partial_capture_handling_i_c0038_0 = True
add_tests_for_partial_capture_handling_i_c0038_1 = True
add_tests_for_partial_capture_handling_i_c0038_2 = True
add_tests_for_partial_capture_handling_i_c0038_3 = True
add_tests_for_partial_capture_handling_i_c0038_4 = True
add_tests_for_partial_capture_handling_i_c0038_5 = True
add_tests_for_partial_capture_handling_i_c0038_6 = True
add_tests_for_partial_capture_handling_i_c0038_7 = True
add_tests_for_partial_capture_handling_i_c0038_8 = True
add_tests_for_partial_capture_handling_i_c0038_9 = True
add_tests_for_partial_capture_handling_i_c0038_10 = True
add_tests_for_partial_capture_handling_i_c0038_11 = True
add_tests_for_partial_capture_handling_i_c0038_12 = True
add_tests_for_partial_capture_handling_i_c0038_13 = True
add_tests_for_partial_capture_handling_i_c0038_14 = True
add_tests_for_partial_capture_handling_i_c0038_15 = True
add_tests_for_partial_capture_handling_i_c0038_16 = True
add_tests_for_partial_capture_handling_i_c0038_17 = True
add_tests_for_partial_capture_handling_i_c0038_18 = True
add_tests_for_partial_capture_handling_i_c0038_19 = True
add_tests_for_partial_capture_handling_i_c0038_20 = True


# Support partial capture handling
support_partial_capture_handling_c0061_0 = True
support_partial_capture_handling_c0061_1 = True
support_partial_capture_handling_c0061_2 = True
support_partial_capture_handling_c0061_3 = True
support_partial_capture_handling_c0061_4 = True
support_partial_capture_handling_c0061_5 = True
