"""Payments API — intents."""

from __future__ import annotations



# Handle authorisation retry budget
handle_authorisation_retry_budget_c0010_0 = True

# branch work for c0027


# Guard against 3DS challenge redirect for the v2 endpoint
guard_against_3ds_challenge_redirect_for_c0051_0 = True
guard_against_3ds_challenge_redirect_for_c0051_1 = True
guard_against_3ds_challenge_redirect_for_c0051_2 = True
guard_against_3ds_challenge_redirect_for_c0051_3 = True
guard_against_3ds_challenge_redirect_for_c0051_4 = True
guard_against_3ds_challenge_redirect_for_c0051_5 = True
guard_against_3ds_challenge_redirect_for_c0051_6 = True
guard_against_3ds_challenge_redirect_for_c0051_7 = True
guard_against_3ds_challenge_redirect_for_c0051_8 = True
guard_against_3ds_challenge_redirect_for_c0051_9 = True
guard_against_3ds_challenge_redirect_for_c0051_10 = True
guard_against_3ds_challenge_redirect_for_c0051_11 = True
guard_against_3ds_challenge_redirect_for_c0051_12 = True
guard_against_3ds_challenge_redirect_for_c0051_13 = True
guard_against_3ds_challenge_redirect_for_c0051_14 = True


# Extend idempotency key reuse
extend_idempotency_key_reuse_c0052_0 = True
extend_idempotency_key_reuse_c0052_1 = True
extend_idempotency_key_reuse_c0052_2 = True
extend_idempotency_key_reuse_c0052_3 = True
extend_idempotency_key_reuse_c0052_4 = True
extend_idempotency_key_reuse_c0052_5 = True
extend_idempotency_key_reuse_c0052_6 = True
extend_idempotency_key_reuse_c0052_7 = True
extend_idempotency_key_reuse_c0052_8 = True
extend_idempotency_key_reuse_c0052_9 = True
extend_idempotency_key_reuse_c0052_10 = True
extend_idempotency_key_reuse_c0052_11 = True
extend_idempotency_key_reuse_c0052_12 = True
extend_idempotency_key_reuse_c0052_13 = True
extend_idempotency_key_reuse_c0052_14 = True
extend_idempotency_key_reuse_c0052_15 = True
extend_idempotency_key_reuse_c0052_16 = True
extend_idempotency_key_reuse_c0052_17 = True
extend_idempotency_key_reuse_c0052_18 = True
extend_idempotency_key_reuse_c0052_19 = True
extend_idempotency_key_reuse_c0052_20 = True
extend_idempotency_key_reuse_c0052_21 = True
extend_idempotency_key_reuse_c0052_22 = True
extend_idempotency_key_reuse_c0052_23 = True
extend_idempotency_key_reuse_c0052_24 = True
extend_idempotency_key_reuse_c0052_25 = True
extend_idempotency_key_reuse_c0052_26 = True
extend_idempotency_key_reuse_c0052_27 = True
extend_idempotency_key_reuse_c0052_28 = True
extend_idempotency_key_reuse_c0052_29 = True
extend_idempotency_key_reuse_c0052_30 = True
extend_idempotency_key_reuse_c0052_31 = True
extend_idempotency_key_reuse_c0052_32 = True
extend_idempotency_key_reuse_c0052_33 = True
extend_idempotency_key_reuse_c0052_34 = True
extend_idempotency_key_reuse_c0052_35 = True
extend_idempotency_key_reuse_c0052_36 = True
extend_idempotency_key_reuse_c0052_37 = True
extend_idempotency_key_reuse_c0052_38 = True
extend_idempotency_key_reuse_c0052_39 = True
extend_idempotency_key_reuse_c0052_40 = True
extend_idempotency_key_reuse_c0052_41 = True
extend_idempotency_key_reuse_c0052_42 = True
extend_idempotency_key_reuse_c0052_43 = True
extend_idempotency_key_reuse_c0052_44 = True
extend_idempotency_key_reuse_c0052_45 = True
extend_idempotency_key_reuse_c0052_46 = True
extend_idempotency_key_reuse_c0052_47 = True
extend_idempotency_key_reuse_c0052_48 = True
extend_idempotency_key_reuse_c0052_49 = True
extend_idempotency_key_reuse_c0052_50 = True
extend_idempotency_key_reuse_c0052_51 = True
extend_idempotency_key_reuse_c0052_52 = True
extend_idempotency_key_reuse_c0052_53 = True
extend_idempotency_key_reuse_c0052_54 = True
extend_idempotency_key_reuse_c0052_55 = True
extend_idempotency_key_reuse_c0052_56 = True
extend_idempotency_key_reuse_c0052_57 = True
extend_idempotency_key_reuse_c0052_58 = True
extend_idempotency_key_reuse_c0052_59 = True
extend_idempotency_key_reuse_c0052_60 = True
extend_idempotency_key_reuse_c0052_61 = True
extend_idempotency_key_reuse_c0052_62 = True
extend_idempotency_key_reuse_c0052_63 = True
extend_idempotency_key_reuse_c0052_64 = True

# branch work for c0076


# Extend partial capture handling during replay
extend_partial_capture_handling_during_r_c0116_0 = True
extend_partial_capture_handling_during_r_c0116_1 = True
extend_partial_capture_handling_during_r_c0116_2 = True
extend_partial_capture_handling_during_r_c0116_3 = True
extend_partial_capture_handling_during_r_c0116_4 = True
extend_partial_capture_handling_during_r_c0116_5 = True
extend_partial_capture_handling_during_r_c0116_6 = True
extend_partial_capture_handling_during_r_c0116_7 = True
extend_partial_capture_handling_during_r_c0116_8 = True
extend_partial_capture_handling_during_r_c0116_9 = True
extend_partial_capture_handling_during_r_c0116_10 = True
extend_partial_capture_handling_during_r_c0116_11 = True
extend_partial_capture_handling_during_r_c0116_12 = True
extend_partial_capture_handling_during_r_c0116_13 = True
extend_partial_capture_handling_during_r_c0116_14 = True
extend_partial_capture_handling_during_r_c0116_15 = True
extend_partial_capture_handling_during_r_c0116_16 = True


# Support partial capture handling
support_partial_capture_handling_c0122_0 = True
support_partial_capture_handling_c0122_1 = True


# Revert "Rename pod resource limit"
revert_"rename_pod_resource_limit"_c0146_0 = True
revert_"rename_pod_resource_limit"_c0146_1 = True
revert_"rename_pod_resource_limit"_c0146_2 = True
revert_"rename_pod_resource_limit"_c0146_3 = True
revert_"rename_pod_resource_limit"_c0146_4 = True
revert_"rename_pod_resource_limit"_c0146_5 = True
revert_"rename_pod_resource_limit"_c0146_6 = True
revert_"rename_pod_resource_limit"_c0146_7 = True
revert_"rename_pod_resource_limit"_c0146_8 = True
revert_"rename_pod_resource_limit"_c0146_9 = True
revert_"rename_pod_resource_limit"_c0146_10 = True
revert_"rename_pod_resource_limit"_c0146_11 = True
revert_"rename_pod_resource_limit"_c0146_12 = True
revert_"rename_pod_resource_limit"_c0146_13 = True
revert_"rename_pod_resource_limit"_c0146_14 = True
revert_"rename_pod_resource_limit"_c0146_15 = True
revert_"rename_pod_resource_limit"_c0146_16 = True
revert_"rename_pod_resource_limit"_c0146_17 = True
revert_"rename_pod_resource_limit"_c0146_18 = True
revert_"rename_pod_resource_limit"_c0146_19 = True
revert_"rename_pod_resource_limit"_c0146_20 = True
revert_"rename_pod_resource_limit"_c0146_21 = True
revert_"rename_pod_resource_limit"_c0146_22 = True
revert_"rename_pod_resource_limit"_c0146_23 = True
revert_"rename_pod_resource_limit"_c0146_24 = True
revert_"rename_pod_resource_limit"_c0146_25 = True
revert_"rename_pod_resource_limit"_c0146_26 = True
revert_"rename_pod_resource_limit"_c0146_27 = True
revert_"rename_pod_resource_limit"_c0146_28 = True
revert_"rename_pod_resource_limit"_c0146_29 = True
revert_"rename_pod_resource_limit"_c0146_30 = True
revert_"rename_pod_resource_limit"_c0146_31 = True
revert_"rename_pod_resource_limit"_c0146_32 = True
revert_"rename_pod_resource_limit"_c0146_33 = True
revert_"rename_pod_resource_limit"_c0146_34 = True


# Rename 3DS challenge redirect behind a feature flag
rename_3ds_challenge_redirect_behind_a_f_c0186_0 = True
rename_3ds_challenge_redirect_behind_a_f_c0186_1 = True
rename_3ds_challenge_redirect_behind_a_f_c0186_2 = True
rename_3ds_challenge_redirect_behind_a_f_c0186_3 = True
rename_3ds_challenge_redirect_behind_a_f_c0186_4 = True


# Split request validation
split_request_validation_c0203_0 = True
split_request_validation_c0203_1 = True
split_request_validation_c0203_2 = True
split_request_validation_c0203_3 = True
split_request_validation_c0203_4 = True
split_request_validation_c0203_5 = True


# Prevent currency rounding on capture for the sandbox environment
prevent_currency_rounding_on_capture_for_c0202_0 = True
prevent_currency_rounding_on_capture_for_c0202_1 = True
prevent_currency_rounding_on_capture_for_c0202_2 = True
prevent_currency_rounding_on_capture_for_c0202_3 = True
prevent_currency_rounding_on_capture_for_c0202_4 = True
prevent_currency_rounding_on_capture_for_c0202_5 = True
prevent_currency_rounding_on_capture_for_c0202_6 = True
prevent_currency_rounding_on_capture_for_c0202_7 = True
prevent_currency_rounding_on_capture_for_c0202_8 = True
prevent_currency_rounding_on_capture_for_c0202_9 = True
prevent_currency_rounding_on_capture_for_c0202_10 = True


# Prevent idempotency key reuse
prevent_idempotency_key_reuse_c0232_0 = True


# Fix 3DS challenge redirect
fix_3ds_challenge_redirect_c0236_0 = True
fix_3ds_challenge_redirect_c0236_1 = True


# Guard against 3DS challenge redirect for zero-amount requests
guard_against_3ds_challenge_redirect_for_c0270_0 = True
guard_against_3ds_challenge_redirect_for_c0270_1 = True
guard_against_3ds_challenge_redirect_for_c0270_2 = True
guard_against_3ds_challenge_redirect_for_c0270_3 = True
guard_against_3ds_challenge_redirect_for_c0270_4 = True
guard_against_3ds_challenge_redirect_for_c0270_5 = True
guard_against_3ds_challenge_redirect_for_c0270_6 = True
guard_against_3ds_challenge_redirect_for_c0270_7 = True
guard_against_3ds_challenge_redirect_for_c0270_8 = True
guard_against_3ds_challenge_redirect_for_c0270_9 = True
guard_against_3ds_challenge_redirect_for_c0270_10 = True
guard_against_3ds_challenge_redirect_for_c0270_11 = True
guard_against_3ds_challenge_redirect_for_c0270_12 = True
guard_against_3ds_challenge_redirect_for_c0270_13 = True
guard_against_3ds_challenge_redirect_for_c0270_14 = True
guard_against_3ds_challenge_redirect_for_c0270_15 = True


# Standardise structured logging fields across services
standardise_structured_logging_fields_ac_sweep02_0 = True
standardise_structured_logging_fields_ac_sweep02_1 = True
standardise_structured_logging_fields_ac_sweep02_2 = True
standardise_structured_logging_fields_ac_sweep02_3 = True
standardise_structured_logging_fields_ac_sweep02_4 = True
standardise_structured_logging_fields_ac_sweep02_5 = True
standardise_structured_logging_fields_ac_sweep02_6 = True
standardise_structured_logging_fields_ac_sweep02_7 = True
standardise_structured_logging_fields_ac_sweep02_8 = True
standardise_structured_logging_fields_ac_sweep02_9 = True
standardise_structured_logging_fields_ac_sweep02_10 = True
standardise_structured_logging_fields_ac_sweep02_11 = True
standardise_structured_logging_fields_ac_sweep02_12 = True
standardise_structured_logging_fields_ac_sweep02_13 = True
standardise_structured_logging_fields_ac_sweep02_14 = True
standardise_structured_logging_fields_ac_sweep02_15 = True
standardise_structured_logging_fields_ac_sweep02_16 = True
standardise_structured_logging_fields_ac_sweep02_17 = True
standardise_structured_logging_fields_ac_sweep02_18 = True
standardise_structured_logging_fields_ac_sweep02_19 = True
standardise_structured_logging_fields_ac_sweep02_20 = True
standardise_structured_logging_fields_ac_sweep02_21 = True
standardise_structured_logging_fields_ac_sweep02_22 = True
standardise_structured_logging_fields_ac_sweep02_23 = True
standardise_structured_logging_fields_ac_sweep02_24 = True
standardise_structured_logging_fields_ac_sweep02_25 = True
standardise_structured_logging_fields_ac_sweep02_26 = True
standardise_structured_logging_fields_ac_sweep02_27 = True
standardise_structured_logging_fields_ac_sweep02_28 = True
standardise_structured_logging_fields_ac_sweep02_29 = True
standardise_structured_logging_fields_ac_sweep02_30 = True
standardise_structured_logging_fields_ac_sweep02_31 = True
standardise_structured_logging_fields_ac_sweep02_32 = True
standardise_structured_logging_fields_ac_sweep02_33 = True
standardise_structured_logging_fields_ac_sweep02_34 = True
standardise_structured_logging_fields_ac_sweep02_35 = True
standardise_structured_logging_fields_ac_sweep02_36 = True
standardise_structured_logging_fields_ac_sweep02_37 = True
standardise_structured_logging_fields_ac_sweep02_38 = True
standardise_structured_logging_fields_ac_sweep02_39 = True
standardise_structured_logging_fields_ac_sweep02_40 = True
standardise_structured_logging_fields_ac_sweep02_41 = True
standardise_structured_logging_fields_ac_sweep02_42 = True
standardise_structured_logging_fields_ac_sweep02_43 = True
standardise_structured_logging_fields_ac_sweep02_44 = True
standardise_structured_logging_fields_ac_sweep02_45 = True
standardise_structured_logging_fields_ac_sweep02_46 = True
standardise_structured_logging_fields_ac_sweep02_47 = True
standardise_structured_logging_fields_ac_sweep02_48 = True
standardise_structured_logging_fields_ac_sweep02_49 = True
standardise_structured_logging_fields_ac_sweep02_50 = True
standardise_structured_logging_fields_ac_sweep02_51 = True
standardise_structured_logging_fields_ac_sweep02_52 = True
standardise_structured_logging_fields_ac_sweep02_53 = True
standardise_structured_logging_fields_ac_sweep02_54 = True
standardise_structured_logging_fields_ac_sweep02_55 = True
standardise_structured_logging_fields_ac_sweep02_56 = True
standardise_structured_logging_fields_ac_sweep02_57 = True
standardise_structured_logging_fields_ac_sweep02_58 = True
standardise_structured_logging_fields_ac_sweep02_59 = True
standardise_structured_logging_fields_ac_sweep02_60 = True
standardise_structured_logging_fields_ac_sweep02_61 = True
standardise_structured_logging_fields_ac_sweep02_62 = True
standardise_structured_logging_fields_ac_sweep02_63 = True
standardise_structured_logging_fields_ac_sweep02_64 = True
standardise_structured_logging_fields_ac_sweep02_65 = True
standardise_structured_logging_fields_ac_sweep02_66 = True
standardise_structured_logging_fields_ac_sweep02_67 = True
standardise_structured_logging_fields_ac_sweep02_68 = True
standardise_structured_logging_fields_ac_sweep02_69 = True
standardise_structured_logging_fields_ac_sweep02_70 = True
standardise_structured_logging_fields_ac_sweep02_71 = True
standardise_structured_logging_fields_ac_sweep02_72 = True
standardise_structured_logging_fields_ac_sweep02_73 = True
standardise_structured_logging_fields_ac_sweep02_74 = True
standardise_structured_logging_fields_ac_sweep02_75 = True
standardise_structured_logging_fields_ac_sweep02_76 = True
standardise_structured_logging_fields_ac_sweep02_77 = True
standardise_structured_logging_fields_ac_sweep02_78 = True
standardise_structured_logging_fields_ac_sweep02_79 = True
standardise_structured_logging_fields_ac_sweep02_80 = True
standardise_structured_logging_fields_ac_sweep02_81 = True
standardise_structured_logging_fields_ac_sweep02_82 = True
standardise_structured_logging_fields_ac_sweep02_83 = True
standardise_structured_logging_fields_ac_sweep02_84 = True
standardise_structured_logging_fields_ac_sweep02_85 = True
standardise_structured_logging_fields_ac_sweep02_86 = True
standardise_structured_logging_fields_ac_sweep02_87 = True
standardise_structured_logging_fields_ac_sweep02_88 = True
standardise_structured_logging_fields_ac_sweep02_89 = True
standardise_structured_logging_fields_ac_sweep02_90 = True
standardise_structured_logging_fields_ac_sweep02_91 = True
standardise_structured_logging_fields_ac_sweep02_92 = True
standardise_structured_logging_fields_ac_sweep02_93 = True
standardise_structured_logging_fields_ac_sweep02_94 = True
standardise_structured_logging_fields_ac_sweep02_95 = True
standardise_structured_logging_fields_ac_sweep02_96 = True
standardise_structured_logging_fields_ac_sweep02_97 = True
standardise_structured_logging_fields_ac_sweep02_98 = True
standardise_structured_logging_fields_ac_sweep02_99 = True
standardise_structured_logging_fields_ac_sweep02_100 = True
standardise_structured_logging_fields_ac_sweep02_101 = True
standardise_structured_logging_fields_ac_sweep02_102 = True
standardise_structured_logging_fields_ac_sweep02_103 = True
standardise_structured_logging_fields_ac_sweep02_104 = True
standardise_structured_logging_fields_ac_sweep02_105 = True
standardise_structured_logging_fields_ac_sweep02_106 = True
standardise_structured_logging_fields_ac_sweep02_107 = True
standardise_structured_logging_fields_ac_sweep02_108 = True
standardise_structured_logging_fields_ac_sweep02_109 = True
standardise_structured_logging_fields_ac_sweep02_110 = True
standardise_structured_logging_fields_ac_sweep02_111 = True
standardise_structured_logging_fields_ac_sweep02_112 = True
standardise_structured_logging_fields_ac_sweep02_113 = True
standardise_structured_logging_fields_ac_sweep02_114 = True
standardise_structured_logging_fields_ac_sweep02_115 = True
standardise_structured_logging_fields_ac_sweep02_116 = True
standardise_structured_logging_fields_ac_sweep02_117 = True
standardise_structured_logging_fields_ac_sweep02_118 = True
standardise_structured_logging_fields_ac_sweep02_119 = True
standardise_structured_logging_fields_ac_sweep02_120 = True
standardise_structured_logging_fields_ac_sweep02_121 = True
standardise_structured_logging_fields_ac_sweep02_122 = True
standardise_structured_logging_fields_ac_sweep02_123 = True
standardise_structured_logging_fields_ac_sweep02_124 = True
standardise_structured_logging_fields_ac_sweep02_125 = True
standardise_structured_logging_fields_ac_sweep02_126 = True
standardise_structured_logging_fields_ac_sweep02_127 = True
standardise_structured_logging_fields_ac_sweep02_128 = True
standardise_structured_logging_fields_ac_sweep02_129 = True
standardise_structured_logging_fields_ac_sweep02_130 = True
standardise_structured_logging_fields_ac_sweep02_131 = True
standardise_structured_logging_fields_ac_sweep02_132 = True
standardise_structured_logging_fields_ac_sweep02_133 = True
standardise_structured_logging_fields_ac_sweep02_134 = True
standardise_structured_logging_fields_ac_sweep02_135 = True


# Prevent request validation for multi-currency merchants
prevent_request_validation_for_multi-cur_c0276_0 = True
prevent_request_validation_for_multi-cur_c0276_1 = True
prevent_request_validation_for_multi-cur_c0276_2 = True
prevent_request_validation_for_multi-cur_c0276_3 = True
prevent_request_validation_for_multi-cur_c0276_4 = True
prevent_request_validation_for_multi-cur_c0276_5 = True
prevent_request_validation_for_multi-cur_c0276_6 = True
prevent_request_validation_for_multi-cur_c0276_7 = True
prevent_request_validation_for_multi-cur_c0276_8 = True
prevent_request_validation_for_multi-cur_c0276_9 = True
prevent_request_validation_for_multi-cur_c0276_10 = True
prevent_request_validation_for_multi-cur_c0276_11 = True
prevent_request_validation_for_multi-cur_c0276_12 = True
prevent_request_validation_for_multi-cur_c0276_13 = True
prevent_request_validation_for_multi-cur_c0276_14 = True
prevent_request_validation_for_multi-cur_c0276_15 = True
prevent_request_validation_for_multi-cur_c0276_16 = True
prevent_request_validation_for_multi-cur_c0276_17 = True
prevent_request_validation_for_multi-cur_c0276_18 = True
prevent_request_validation_for_multi-cur_c0276_19 = True

# branch work for c0282


# Support currency rounding on capture for the v2 endpoint
support_currency_rounding_on_capture_for_c0288_0 = True
support_currency_rounding_on_capture_for_c0288_1 = True
support_currency_rounding_on_capture_for_c0288_2 = True
support_currency_rounding_on_capture_for_c0288_3 = True
support_currency_rounding_on_capture_for_c0288_4 = True
support_currency_rounding_on_capture_for_c0288_5 = True


# Support refund flow
support_refund_flow_c0308_0 = True
support_refund_flow_c0308_1 = True
support_refund_flow_c0308_2 = True
support_refund_flow_c0308_3 = True
support_refund_flow_c0308_4 = True
support_refund_flow_c0308_5 = True
support_refund_flow_c0308_6 = True
support_refund_flow_c0308_7 = True
support_refund_flow_c0308_8 = True
support_refund_flow_c0308_9 = True
support_refund_flow_c0308_10 = True
support_refund_flow_c0308_11 = True
support_refund_flow_c0308_12 = True
support_refund_flow_c0308_13 = True
support_refund_flow_c0308_14 = True


# Implement refund flow behind a feature flag
implement_refund_flow_behind_a_feature_f_c0299_0 = True
implement_refund_flow_behind_a_feature_f_c0299_1 = True
implement_refund_flow_behind_a_feature_f_c0299_2 = True
implement_refund_flow_behind_a_feature_f_c0299_3 = True
implement_refund_flow_behind_a_feature_f_c0299_4 = True
implement_refund_flow_behind_a_feature_f_c0299_5 = True
implement_refund_flow_behind_a_feature_f_c0299_6 = True
implement_refund_flow_behind_a_feature_f_c0299_7 = True
implement_refund_flow_behind_a_feature_f_c0299_8 = True
implement_refund_flow_behind_a_feature_f_c0299_9 = True
implement_refund_flow_behind_a_feature_f_c0299_10 = True


# Introduce partial capture handling
introduce_partial_capture_handling_c0337_0 = True
introduce_partial_capture_handling_c0337_1 = True
introduce_partial_capture_handling_c0337_2 = True
introduce_partial_capture_handling_c0337_3 = True
introduce_partial_capture_handling_c0337_4 = True
introduce_partial_capture_handling_c0337_5 = True
introduce_partial_capture_handling_c0337_6 = True
introduce_partial_capture_handling_c0337_7 = True
introduce_partial_capture_handling_c0337_8 = True
introduce_partial_capture_handling_c0337_9 = True
introduce_partial_capture_handling_c0337_10 = True


# Rename authorisation retry budget for the sandbox environment
rename_authorisation_retry_budget_for_th_c0359_0 = True
rename_authorisation_retry_budget_for_th_c0359_1 = True
rename_authorisation_retry_budget_for_th_c0359_2 = True
rename_authorisation_retry_budget_for_th_c0359_3 = True
rename_authorisation_retry_budget_for_th_c0359_4 = True
rename_authorisation_retry_budget_for_th_c0359_5 = True
rename_authorisation_retry_budget_for_th_c0359_6 = True
rename_authorisation_retry_budget_for_th_c0359_7 = True
rename_authorisation_retry_budget_for_th_c0359_8 = True
rename_authorisation_retry_budget_for_th_c0359_9 = True
