"""Payments API — refunds."""

from __future__ import annotations



# Support intent expiry sweep
support_intent_expiry_sweep_c0026_0 = True
support_intent_expiry_sweep_c0026_1 = True
support_intent_expiry_sweep_c0026_2 = True
support_intent_expiry_sweep_c0026_3 = True
support_intent_expiry_sweep_c0026_4 = True
support_intent_expiry_sweep_c0026_5 = True
support_intent_expiry_sweep_c0026_6 = True
support_intent_expiry_sweep_c0026_7 = True
support_intent_expiry_sweep_c0026_8 = True
support_intent_expiry_sweep_c0026_9 = True
support_intent_expiry_sweep_c0026_10 = True
support_intent_expiry_sweep_c0026_11 = True
support_intent_expiry_sweep_c0026_12 = True
support_intent_expiry_sweep_c0026_13 = True
support_intent_expiry_sweep_c0026_14 = True
support_intent_expiry_sweep_c0026_15 = True
support_intent_expiry_sweep_c0026_16 = True
support_intent_expiry_sweep_c0026_17 = True
support_intent_expiry_sweep_c0026_18 = True


# Refactor error envelope
refactor_error_envelope_c0021_0 = True
refactor_error_envelope_c0021_1 = True
refactor_error_envelope_c0021_2 = True
refactor_error_envelope_c0021_3 = True


# Simplify request validation
simplify_request_validation_c0041_0 = True
simplify_request_validation_c0041_1 = True
simplify_request_validation_c0041_2 = True
simplify_request_validation_c0041_3 = True
simplify_request_validation_c0041_4 = True
simplify_request_validation_c0041_5 = True
simplify_request_validation_c0041_6 = True
simplify_request_validation_c0041_7 = True
simplify_request_validation_c0041_8 = True
simplify_request_validation_c0041_9 = True
simplify_request_validation_c0041_10 = True
simplify_request_validation_c0041_11 = True
simplify_request_validation_c0041_12 = True
simplify_request_validation_c0041_13 = True
simplify_request_validation_c0041_14 = True
simplify_request_validation_c0041_15 = True
simplify_request_validation_c0041_16 = True
simplify_request_validation_c0041_17 = True
simplify_request_validation_c0041_18 = True
simplify_request_validation_c0041_19 = True
simplify_request_validation_c0041_20 = True
simplify_request_validation_c0041_21 = True
simplify_request_validation_c0041_22 = True


# Introduce partial capture handling
introduce_partial_capture_handling_c0070_0 = True
introduce_partial_capture_handling_c0070_1 = True
introduce_partial_capture_handling_c0070_2 = True
introduce_partial_capture_handling_c0070_3 = True
introduce_partial_capture_handling_c0070_4 = True
introduce_partial_capture_handling_c0070_5 = True


# Cover request validation
cover_request_validation_c0071_0 = True
cover_request_validation_c0071_1 = True
cover_request_validation_c0071_2 = True


# Extend partial capture handling during replay
extend_partial_capture_handling_during_r_c0116_0 = True
extend_partial_capture_handling_during_r_c0116_1 = True
extend_partial_capture_handling_during_r_c0116_2 = True
extend_partial_capture_handling_during_r_c0116_3 = True
extend_partial_capture_handling_during_r_c0116_4 = True
extend_partial_capture_handling_during_r_c0116_5 = True
extend_partial_capture_handling_during_r_c0116_6 = True
extend_partial_capture_handling_during_r_c0116_7 = True
extend_partial_capture_handling_during_r_c0116_8 = True
extend_partial_capture_handling_during_r_c0116_9 = True
extend_partial_capture_handling_during_r_c0116_10 = True
extend_partial_capture_handling_during_r_c0116_11 = True
extend_partial_capture_handling_during_r_c0116_12 = True
extend_partial_capture_handling_during_r_c0116_13 = True
extend_partial_capture_handling_during_r_c0116_14 = True
extend_partial_capture_handling_during_r_c0116_15 = True
extend_partial_capture_handling_during_r_c0116_16 = True


# Rename refund flow
rename_refund_flow_c0170_0 = True
rename_refund_flow_c0170_1 = True


# Support error envelope during replay
support_error_envelope_during_replay_c0176_0 = True
support_error_envelope_during_replay_c0176_1 = True
support_error_envelope_during_replay_c0176_2 = True
support_error_envelope_during_replay_c0176_3 = True
support_error_envelope_during_replay_c0176_4 = True
support_error_envelope_during_replay_c0176_5 = True
support_error_envelope_during_replay_c0176_6 = True
support_error_envelope_during_replay_c0176_7 = True
support_error_envelope_during_replay_c0176_8 = True
support_error_envelope_during_replay_c0176_9 = True
support_error_envelope_during_replay_c0176_10 = True
support_error_envelope_during_replay_c0176_11 = True
support_error_envelope_during_replay_c0176_12 = True
support_error_envelope_during_replay_c0176_13 = True


# Rename 3DS challenge redirect behind a feature flag
rename_3ds_challenge_redirect_behind_a_f_c0186_0 = True
rename_3ds_challenge_redirect_behind_a_f_c0186_1 = True
rename_3ds_challenge_redirect_behind_a_f_c0186_2 = True
rename_3ds_challenge_redirect_behind_a_f_c0186_3 = True
rename_3ds_challenge_redirect_behind_a_f_c0186_4 = True


# Prevent idempotency key reuse
prevent_idempotency_key_reuse_c0232_0 = True


# Extend authorisation retry budget
extend_authorisation_retry_budget_c0227_0 = True
extend_authorisation_retry_budget_c0227_1 = True
extend_authorisation_retry_budget_c0227_2 = True
extend_authorisation_retry_budget_c0227_3 = True
extend_authorisation_retry_budget_c0227_4 = True
extend_authorisation_retry_budget_c0227_5 = True
extend_authorisation_retry_budget_c0227_6 = True
extend_authorisation_retry_budget_c0227_7 = True
extend_authorisation_retry_budget_c0227_8 = True
extend_authorisation_retry_budget_c0227_9 = True
extend_authorisation_retry_budget_c0227_10 = True
extend_authorisation_retry_budget_c0227_11 = True


# Implement intent expiry sweep for the sandbox environment
implement_intent_expiry_sweep_for_the_sa_c0245_0 = True
implement_intent_expiry_sweep_for_the_sa_c0245_1 = True
implement_intent_expiry_sweep_for_the_sa_c0245_2 = True
implement_intent_expiry_sweep_for_the_sa_c0245_3 = True


# Harden tests around refund flow
harden_tests_around_refund_flow_c0272_0 = True
harden_tests_around_refund_flow_c0272_1 = True


# Standardise structured logging fields across services
standardise_structured_logging_fields_ac_sweep02_0 = True
standardise_structured_logging_fields_ac_sweep02_1 = True
standardise_structured_logging_fields_ac_sweep02_2 = True
standardise_structured_logging_fields_ac_sweep02_3 = True
standardise_structured_logging_fields_ac_sweep02_4 = True
standardise_structured_logging_fields_ac_sweep02_5 = True
standardise_structured_logging_fields_ac_sweep02_6 = True
standardise_structured_logging_fields_ac_sweep02_7 = True
standardise_structured_logging_fields_ac_sweep02_8 = True
standardise_structured_logging_fields_ac_sweep02_9 = True
standardise_structured_logging_fields_ac_sweep02_10 = True
standardise_structured_logging_fields_ac_sweep02_11 = True
standardise_structured_logging_fields_ac_sweep02_12 = True
standardise_structured_logging_fields_ac_sweep02_13 = True
standardise_structured_logging_fields_ac_sweep02_14 = True
standardise_structured_logging_fields_ac_sweep02_15 = True
standardise_structured_logging_fields_ac_sweep02_16 = True
standardise_structured_logging_fields_ac_sweep02_17 = True
standardise_structured_logging_fields_ac_sweep02_18 = True
standardise_structured_logging_fields_ac_sweep02_19 = True
standardise_structured_logging_fields_ac_sweep02_20 = True
standardise_structured_logging_fields_ac_sweep02_21 = True
standardise_structured_logging_fields_ac_sweep02_22 = True
standardise_structured_logging_fields_ac_sweep02_23 = True
standardise_structured_logging_fields_ac_sweep02_24 = True
standardise_structured_logging_fields_ac_sweep02_25 = True
standardise_structured_logging_fields_ac_sweep02_26 = True
standardise_structured_logging_fields_ac_sweep02_27 = True
standardise_structured_logging_fields_ac_sweep02_28 = True
standardise_structured_logging_fields_ac_sweep02_29 = True
standardise_structured_logging_fields_ac_sweep02_30 = True
standardise_structured_logging_fields_ac_sweep02_31 = True
standardise_structured_logging_fields_ac_sweep02_32 = True
standardise_structured_logging_fields_ac_sweep02_33 = True
standardise_structured_logging_fields_ac_sweep02_34 = True
standardise_structured_logging_fields_ac_sweep02_35 = True
standardise_structured_logging_fields_ac_sweep02_36 = True
standardise_structured_logging_fields_ac_sweep02_37 = True
standardise_structured_logging_fields_ac_sweep02_38 = True
standardise_structured_logging_fields_ac_sweep02_39 = True
standardise_structured_logging_fields_ac_sweep02_40 = True
standardise_structured_logging_fields_ac_sweep02_41 = True
standardise_structured_logging_fields_ac_sweep02_42 = True
standardise_structured_logging_fields_ac_sweep02_43 = True
standardise_structured_logging_fields_ac_sweep02_44 = True
standardise_structured_logging_fields_ac_sweep02_45 = True
standardise_structured_logging_fields_ac_sweep02_46 = True
standardise_structured_logging_fields_ac_sweep02_47 = True
standardise_structured_logging_fields_ac_sweep02_48 = True
standardise_structured_logging_fields_ac_sweep02_49 = True
standardise_structured_logging_fields_ac_sweep02_50 = True
standardise_structured_logging_fields_ac_sweep02_51 = True
standardise_structured_logging_fields_ac_sweep02_52 = True
standardise_structured_logging_fields_ac_sweep02_53 = True
standardise_structured_logging_fields_ac_sweep02_54 = True
standardise_structured_logging_fields_ac_sweep02_55 = True
standardise_structured_logging_fields_ac_sweep02_56 = True
standardise_structured_logging_fields_ac_sweep02_57 = True
standardise_structured_logging_fields_ac_sweep02_58 = True
standardise_structured_logging_fields_ac_sweep02_59 = True
standardise_structured_logging_fields_ac_sweep02_60 = True
standardise_structured_logging_fields_ac_sweep02_61 = True
standardise_structured_logging_fields_ac_sweep02_62 = True
standardise_structured_logging_fields_ac_sweep02_63 = True
standardise_structured_logging_fields_ac_sweep02_64 = True
standardise_structured_logging_fields_ac_sweep02_65 = True
standardise_structured_logging_fields_ac_sweep02_66 = True
standardise_structured_logging_fields_ac_sweep02_67 = True
standardise_structured_logging_fields_ac_sweep02_68 = True
standardise_structured_logging_fields_ac_sweep02_69 = True
standardise_structured_logging_fields_ac_sweep02_70 = True
standardise_structured_logging_fields_ac_sweep02_71 = True
standardise_structured_logging_fields_ac_sweep02_72 = True
standardise_structured_logging_fields_ac_sweep02_73 = True
standardise_structured_logging_fields_ac_sweep02_74 = True
standardise_structured_logging_fields_ac_sweep02_75 = True
standardise_structured_logging_fields_ac_sweep02_76 = True
standardise_structured_logging_fields_ac_sweep02_77 = True
standardise_structured_logging_fields_ac_sweep02_78 = True
standardise_structured_logging_fields_ac_sweep02_79 = True
standardise_structured_logging_fields_ac_sweep02_80 = True
standardise_structured_logging_fields_ac_sweep02_81 = True
standardise_structured_logging_fields_ac_sweep02_82 = True
standardise_structured_logging_fields_ac_sweep02_83 = True
standardise_structured_logging_fields_ac_sweep02_84 = True
standardise_structured_logging_fields_ac_sweep02_85 = True
standardise_structured_logging_fields_ac_sweep02_86 = True
standardise_structured_logging_fields_ac_sweep02_87 = True
standardise_structured_logging_fields_ac_sweep02_88 = True
standardise_structured_logging_fields_ac_sweep02_89 = True
standardise_structured_logging_fields_ac_sweep02_90 = True
standardise_structured_logging_fields_ac_sweep02_91 = True
standardise_structured_logging_fields_ac_sweep02_92 = True
standardise_structured_logging_fields_ac_sweep02_93 = True
standardise_structured_logging_fields_ac_sweep02_94 = True
standardise_structured_logging_fields_ac_sweep02_95 = True
standardise_structured_logging_fields_ac_sweep02_96 = True
standardise_structured_logging_fields_ac_sweep02_97 = True
standardise_structured_logging_fields_ac_sweep02_98 = True
standardise_structured_logging_fields_ac_sweep02_99 = True
standardise_structured_logging_fields_ac_sweep02_100 = True
standardise_structured_logging_fields_ac_sweep02_101 = True
standardise_structured_logging_fields_ac_sweep02_102 = True
standardise_structured_logging_fields_ac_sweep02_103 = True
standardise_structured_logging_fields_ac_sweep02_104 = True
standardise_structured_logging_fields_ac_sweep02_105 = True
standardise_structured_logging_fields_ac_sweep02_106 = True
standardise_structured_logging_fields_ac_sweep02_107 = True
standardise_structured_logging_fields_ac_sweep02_108 = True
standardise_structured_logging_fields_ac_sweep02_109 = True
standardise_structured_logging_fields_ac_sweep02_110 = True
standardise_structured_logging_fields_ac_sweep02_111 = True
standardise_structured_logging_fields_ac_sweep02_112 = True
standardise_structured_logging_fields_ac_sweep02_113 = True
standardise_structured_logging_fields_ac_sweep02_114 = True
standardise_structured_logging_fields_ac_sweep02_115 = True
standardise_structured_logging_fields_ac_sweep02_116 = True
standardise_structured_logging_fields_ac_sweep02_117 = True
standardise_structured_logging_fields_ac_sweep02_118 = True
standardise_structured_logging_fields_ac_sweep02_119 = True
standardise_structured_logging_fields_ac_sweep02_120 = True
standardise_structured_logging_fields_ac_sweep02_121 = True
standardise_structured_logging_fields_ac_sweep02_122 = True
standardise_structured_logging_fields_ac_sweep02_123 = True
standardise_structured_logging_fields_ac_sweep02_124 = True
standardise_structured_logging_fields_ac_sweep02_125 = True
standardise_structured_logging_fields_ac_sweep02_126 = True
standardise_structured_logging_fields_ac_sweep02_127 = True
standardise_structured_logging_fields_ac_sweep02_128 = True
standardise_structured_logging_fields_ac_sweep02_129 = True
standardise_structured_logging_fields_ac_sweep02_130 = True
standardise_structured_logging_fields_ac_sweep02_131 = True
standardise_structured_logging_fields_ac_sweep02_132 = True
standardise_structured_logging_fields_ac_sweep02_133 = True
standardise_structured_logging_fields_ac_sweep02_134 = True
standardise_structured_logging_fields_ac_sweep02_135 = True


# Support refund flow
support_refund_flow_c0308_0 = True
support_refund_flow_c0308_1 = True
support_refund_flow_c0308_2 = True
support_refund_flow_c0308_3 = True
support_refund_flow_c0308_4 = True
support_refund_flow_c0308_5 = True
support_refund_flow_c0308_6 = True
support_refund_flow_c0308_7 = True
support_refund_flow_c0308_8 = True
support_refund_flow_c0308_9 = True
support_refund_flow_c0308_10 = True
support_refund_flow_c0308_11 = True
support_refund_flow_c0308_12 = True
support_refund_flow_c0308_13 = True
support_refund_flow_c0308_14 = True


# Tidy idempotency key reuse
tidy_idempotency_key_reuse_c0301_0 = True
tidy_idempotency_key_reuse_c0301_1 = True
tidy_idempotency_key_reuse_c0301_2 = True


# Add tests for partial capture handling
add_tests_for_partial_capture_handling_c0368_0 = True
add_tests_for_partial_capture_handling_c0368_1 = True
add_tests_for_partial_capture_handling_c0368_2 = True


# Extend idempotency key reuse for the v2 endpoint
extend_idempotency_key_reuse_for_the_v2__c0371_0 = True
extend_idempotency_key_reuse_for_the_v2__c0371_1 = True
extend_idempotency_key_reuse_for_the_v2__c0371_2 = True


# Rename settlement_id to settlement_ref across services
rename_settlement_id_to_settlement_ref_a_sweep00_0 = True
rename_settlement_id_to_settlement_ref_a_sweep00_1 = True
rename_settlement_id_to_settlement_ref_a_sweep00_2 = True
rename_settlement_id_to_settlement_ref_a_sweep00_3 = True
rename_settlement_id_to_settlement_ref_a_sweep00_4 = True
rename_settlement_id_to_settlement_ref_a_sweep00_5 = True
rename_settlement_id_to_settlement_ref_a_sweep00_6 = True
rename_settlement_id_to_settlement_ref_a_sweep00_7 = True
rename_settlement_id_to_settlement_ref_a_sweep00_8 = True
rename_settlement_id_to_settlement_ref_a_sweep00_9 = True
rename_settlement_id_to_settlement_ref_a_sweep00_10 = True
rename_settlement_id_to_settlement_ref_a_sweep00_11 = True
rename_settlement_id_to_settlement_ref_a_sweep00_12 = True
rename_settlement_id_to_settlement_ref_a_sweep00_13 = True
rename_settlement_id_to_settlement_ref_a_sweep00_14 = True
rename_settlement_id_to_settlement_ref_a_sweep00_15 = True
rename_settlement_id_to_settlement_ref_a_sweep00_16 = True
rename_settlement_id_to_settlement_ref_a_sweep00_17 = True
rename_settlement_id_to_settlement_ref_a_sweep00_18 = True
rename_settlement_id_to_settlement_ref_a_sweep00_19 = True
rename_settlement_id_to_settlement_ref_a_sweep00_20 = True
rename_settlement_id_to_settlement_ref_a_sweep00_21 = True
rename_settlement_id_to_settlement_ref_a_sweep00_22 = True
rename_settlement_id_to_settlement_ref_a_sweep00_23 = True
rename_settlement_id_to_settlement_ref_a_sweep00_24 = True
rename_settlement_id_to_settlement_ref_a_sweep00_25 = True
rename_settlement_id_to_settlement_ref_a_sweep00_26 = True
rename_settlement_id_to_settlement_ref_a_sweep00_27 = True
rename_settlement_id_to_settlement_ref_a_sweep00_28 = True
rename_settlement_id_to_settlement_ref_a_sweep00_29 = True
rename_settlement_id_to_settlement_ref_a_sweep00_30 = True
rename_settlement_id_to_settlement_ref_a_sweep00_31 = True
rename_settlement_id_to_settlement_ref_a_sweep00_32 = True
rename_settlement_id_to_settlement_ref_a_sweep00_33 = True
rename_settlement_id_to_settlement_ref_a_sweep00_34 = True
rename_settlement_id_to_settlement_ref_a_sweep00_35 = True
rename_settlement_id_to_settlement_ref_a_sweep00_36 = True
rename_settlement_id_to_settlement_ref_a_sweep00_37 = True
rename_settlement_id_to_settlement_ref_a_sweep00_38 = True
rename_settlement_id_to_settlement_ref_a_sweep00_39 = True
rename_settlement_id_to_settlement_ref_a_sweep00_40 = True
rename_settlement_id_to_settlement_ref_a_sweep00_41 = True
rename_settlement_id_to_settlement_ref_a_sweep00_42 = True
rename_settlement_id_to_settlement_ref_a_sweep00_43 = True
rename_settlement_id_to_settlement_ref_a_sweep00_44 = True
rename_settlement_id_to_settlement_ref_a_sweep00_45 = True
rename_settlement_id_to_settlement_ref_a_sweep00_46 = True
rename_settlement_id_to_settlement_ref_a_sweep00_47 = True
rename_settlement_id_to_settlement_ref_a_sweep00_48 = True
rename_settlement_id_to_settlement_ref_a_sweep00_49 = True
rename_settlement_id_to_settlement_ref_a_sweep00_50 = True
rename_settlement_id_to_settlement_ref_a_sweep00_51 = True
rename_settlement_id_to_settlement_ref_a_sweep00_52 = True
rename_settlement_id_to_settlement_ref_a_sweep00_53 = True
rename_settlement_id_to_settlement_ref_a_sweep00_54 = True
rename_settlement_id_to_settlement_ref_a_sweep00_55 = True
rename_settlement_id_to_settlement_ref_a_sweep00_56 = True
rename_settlement_id_to_settlement_ref_a_sweep00_57 = True
rename_settlement_id_to_settlement_ref_a_sweep00_58 = True
rename_settlement_id_to_settlement_ref_a_sweep00_59 = True
rename_settlement_id_to_settlement_ref_a_sweep00_60 = True
rename_settlement_id_to_settlement_ref_a_sweep00_61 = True
rename_settlement_id_to_settlement_ref_a_sweep00_62 = True
rename_settlement_id_to_settlement_ref_a_sweep00_63 = True
rename_settlement_id_to_settlement_ref_a_sweep00_64 = True
rename_settlement_id_to_settlement_ref_a_sweep00_65 = True
rename_settlement_id_to_settlement_ref_a_sweep00_66 = True
rename_settlement_id_to_settlement_ref_a_sweep00_67 = True
rename_settlement_id_to_settlement_ref_a_sweep00_68 = True
rename_settlement_id_to_settlement_ref_a_sweep00_69 = True
rename_settlement_id_to_settlement_ref_a_sweep00_70 = True
rename_settlement_id_to_settlement_ref_a_sweep00_71 = True
rename_settlement_id_to_settlement_ref_a_sweep00_72 = True
rename_settlement_id_to_settlement_ref_a_sweep00_73 = True
rename_settlement_id_to_settlement_ref_a_sweep00_74 = True
rename_settlement_id_to_settlement_ref_a_sweep00_75 = True
rename_settlement_id_to_settlement_ref_a_sweep00_76 = True
rename_settlement_id_to_settlement_ref_a_sweep00_77 = True
rename_settlement_id_to_settlement_ref_a_sweep00_78 = True
rename_settlement_id_to_settlement_ref_a_sweep00_79 = True
rename_settlement_id_to_settlement_ref_a_sweep00_80 = True
rename_settlement_id_to_settlement_ref_a_sweep00_81 = True
rename_settlement_id_to_settlement_ref_a_sweep00_82 = True
rename_settlement_id_to_settlement_ref_a_sweep00_83 = True
rename_settlement_id_to_settlement_ref_a_sweep00_84 = True
rename_settlement_id_to_settlement_ref_a_sweep00_85 = True
rename_settlement_id_to_settlement_ref_a_sweep00_86 = True
rename_settlement_id_to_settlement_ref_a_sweep00_87 = True
rename_settlement_id_to_settlement_ref_a_sweep00_88 = True
rename_settlement_id_to_settlement_ref_a_sweep00_89 = True
rename_settlement_id_to_settlement_ref_a_sweep00_90 = True
rename_settlement_id_to_settlement_ref_a_sweep00_91 = True
rename_settlement_id_to_settlement_ref_a_sweep00_92 = True
rename_settlement_id_to_settlement_ref_a_sweep00_93 = True
rename_settlement_id_to_settlement_ref_a_sweep00_94 = True
rename_settlement_id_to_settlement_ref_a_sweep00_95 = True
rename_settlement_id_to_settlement_ref_a_sweep00_96 = True
rename_settlement_id_to_settlement_ref_a_sweep00_97 = True
rename_settlement_id_to_settlement_ref_a_sweep00_98 = True
rename_settlement_id_to_settlement_ref_a_sweep00_99 = True
rename_settlement_id_to_settlement_ref_a_sweep00_100 = True
rename_settlement_id_to_settlement_ref_a_sweep00_101 = True
rename_settlement_id_to_settlement_ref_a_sweep00_102 = True
rename_settlement_id_to_settlement_ref_a_sweep00_103 = True
rename_settlement_id_to_settlement_ref_a_sweep00_104 = True
rename_settlement_id_to_settlement_ref_a_sweep00_105 = True
rename_settlement_id_to_settlement_ref_a_sweep00_106 = True
rename_settlement_id_to_settlement_ref_a_sweep00_107 = True
rename_settlement_id_to_settlement_ref_a_sweep00_108 = True
rename_settlement_id_to_settlement_ref_a_sweep00_109 = True
rename_settlement_id_to_settlement_ref_a_sweep00_110 = True
rename_settlement_id_to_settlement_ref_a_sweep00_111 = True
rename_settlement_id_to_settlement_ref_a_sweep00_112 = True
rename_settlement_id_to_settlement_ref_a_sweep00_113 = True
rename_settlement_id_to_settlement_ref_a_sweep00_114 = True
rename_settlement_id_to_settlement_ref_a_sweep00_115 = True
rename_settlement_id_to_settlement_ref_a_sweep00_116 = True
rename_settlement_id_to_settlement_ref_a_sweep00_117 = True
rename_settlement_id_to_settlement_ref_a_sweep00_118 = True
rename_settlement_id_to_settlement_ref_a_sweep00_119 = True
rename_settlement_id_to_settlement_ref_a_sweep00_120 = True
