# Infrastructure
terraform {
  required_version = ">= 1.5"
}


# Handle network policy
handle_network_policy_c0005_0 = True


# Guard against pod resource limit when the queue is saturated
guard_against_pod_resource_limit_when_th_c0009_0 = True


# Rename pod resource limit
rename_pod_resource_limit_c0118_0 = True


# Correct network policy on the replica
correct_network_policy_on_the_replica_c0120_0 = True
correct_network_policy_on_the_replica_c0120_1 = True
correct_network_policy_on_the_replica_c0120_2 = True
correct_network_policy_on_the_replica_c0120_3 = True
correct_network_policy_on_the_replica_c0120_4 = True


# Add pod resource limit for multi-currency merchants
add_pod_resource_limit_for_multi-currenc_c0148_0 = True
add_pod_resource_limit_for_multi-currenc_c0148_1 = True
add_pod_resource_limit_for_multi-currenc_c0148_2 = True
add_pod_resource_limit_for_multi-currenc_c0148_3 = True
add_pod_resource_limit_for_multi-currenc_c0148_4 = True
add_pod_resource_limit_for_multi-currenc_c0148_5 = True
add_pod_resource_limit_for_multi-currenc_c0148_6 = True
add_pod_resource_limit_for_multi-currenc_c0148_7 = True
add_pod_resource_limit_for_multi-currenc_c0148_8 = True
add_pod_resource_limit_for_multi-currenc_c0148_9 = True
add_pod_resource_limit_for_multi-currenc_c0148_10 = True
add_pod_resource_limit_for_multi-currenc_c0148_11 = True
add_pod_resource_limit_for_multi-currenc_c0148_12 = True
add_pod_resource_limit_for_multi-currenc_c0148_13 = True
add_pod_resource_limit_for_multi-currenc_c0148_14 = True
add_pod_resource_limit_for_multi-currenc_c0148_15 = True
add_pod_resource_limit_for_multi-currenc_c0148_16 = True
add_pod_resource_limit_for_multi-currenc_c0148_17 = True
add_pod_resource_limit_for_multi-currenc_c0148_18 = True
add_pod_resource_limit_for_multi-currenc_c0148_19 = True
add_pod_resource_limit_for_multi-currenc_c0148_20 = True
add_pod_resource_limit_for_multi-currenc_c0148_21 = True
add_pod_resource_limit_for_multi-currenc_c0148_22 = True
add_pod_resource_limit_for_multi-currenc_c0148_23 = True
add_pod_resource_limit_for_multi-currenc_c0148_24 = True
add_pod_resource_limit_for_multi-currenc_c0148_25 = True
add_pod_resource_limit_for_multi-currenc_c0148_26 = True
add_pod_resource_limit_for_multi-currenc_c0148_27 = True
add_pod_resource_limit_for_multi-currenc_c0148_28 = True
add_pod_resource_limit_for_multi-currenc_c0148_29 = True
add_pod_resource_limit_for_multi-currenc_c0148_30 = True
add_pod_resource_limit_for_multi-currenc_c0148_31 = True
add_pod_resource_limit_for_multi-currenc_c0148_32 = True


# Handle IAM role scope
handle_iam_role_scope_c0295_0 = True
handle_iam_role_scope_c0295_1 = True
handle_iam_role_scope_c0295_2 = True
handle_iam_role_scope_c0295_3 = True
handle_iam_role_scope_c0295_4 = True
handle_iam_role_scope_c0295_5 = True
handle_iam_role_scope_c0295_6 = True
handle_iam_role_scope_c0295_7 = True
handle_iam_role_scope_c0295_8 = True
handle_iam_role_scope_c0295_9 = True
handle_iam_role_scope_c0295_10 = True
handle_iam_role_scope_c0295_11 = True
handle_iam_role_scope_c0295_12 = True
handle_iam_role_scope_c0295_13 = True
handle_iam_role_scope_c0295_14 = True
handle_iam_role_scope_c0295_15 = True
handle_iam_role_scope_c0295_16 = True
handle_iam_role_scope_c0295_17 = True
handle_iam_role_scope_c0295_18 = True
handle_iam_role_scope_c0295_19 = True
handle_iam_role_scope_c0295_20 = True
handle_iam_role_scope_c0295_21 = True
handle_iam_role_scope_c0295_22 = True
handle_iam_role_scope_c0295_23 = True
handle_iam_role_scope_c0295_24 = True
handle_iam_role_scope_c0295_25 = True
handle_iam_role_scope_c0295_26 = True
handle_iam_role_scope_c0295_27 = True
handle_iam_role_scope_c0295_28 = True
handle_iam_role_scope_c0295_29 = True
handle_iam_role_scope_c0295_30 = True
handle_iam_role_scope_c0295_31 = True


# Guard against network policy when the queue is saturated for the sandbox environment
guard_against_network_policy_when_the_qu_c0315_0 = True
guard_against_network_policy_when_the_qu_c0315_1 = True
guard_against_network_policy_when_the_qu_c0315_2 = True
guard_against_network_policy_when_the_qu_c0315_3 = True
guard_against_network_policy_when_the_qu_c0315_4 = True
guard_against_network_policy_when_the_qu_c0315_5 = True
guard_against_network_policy_when_the_qu_c0315_6 = True


# Split pod resource limit for the v2 endpoint
split_pod_resource_limit_for_the_v2_endp_c0320_0 = True
split_pod_resource_limit_for_the_v2_endp_c0320_1 = True
split_pod_resource_limit_for_the_v2_endp_c0320_2 = True
split_pod_resource_limit_for_the_v2_endp_c0320_3 = True
split_pod_resource_limit_for_the_v2_endp_c0320_4 = True
split_pod_resource_limit_for_the_v2_endp_c0320_5 = True
split_pod_resource_limit_for_the_v2_endp_c0320_6 = True
split_pod_resource_limit_for_the_v2_endp_c0320_7 = True
split_pod_resource_limit_for_the_v2_endp_c0320_8 = True
split_pod_resource_limit_for_the_v2_endp_c0320_9 = True
split_pod_resource_limit_for_the_v2_endp_c0320_10 = True
split_pod_resource_limit_for_the_v2_endp_c0320_11 = True
split_pod_resource_limit_for_the_v2_endp_c0320_12 = True
split_pod_resource_limit_for_the_v2_endp_c0320_13 = True
split_pod_resource_limit_for_the_v2_endp_c0320_14 = True
split_pod_resource_limit_for_the_v2_endp_c0320_15 = True
split_pod_resource_limit_for_the_v2_endp_c0320_16 = True
split_pod_resource_limit_for_the_v2_endp_c0320_17 = True


# Correct autoscaling threshold
correct_autoscaling_threshold_c0374_0 = True
correct_autoscaling_threshold_c0374_1 = True
correct_autoscaling_threshold_c0374_2 = True
correct_autoscaling_threshold_c0374_3 = True
correct_autoscaling_threshold_c0374_4 = True
correct_autoscaling_threshold_c0374_5 = True
correct_autoscaling_threshold_c0374_6 = True
correct_autoscaling_threshold_c0374_7 = True
correct_autoscaling_threshold_c0374_8 = True
correct_autoscaling_threshold_c0374_9 = True
correct_autoscaling_threshold_c0374_10 = True


# Rename settlement_id to settlement_ref across services
rename_settlement_id_to_settlement_ref_a_sweep00_0 = True
rename_settlement_id_to_settlement_ref_a_sweep00_1 = True
rename_settlement_id_to_settlement_ref_a_sweep00_2 = True
rename_settlement_id_to_settlement_ref_a_sweep00_3 = True
rename_settlement_id_to_settlement_ref_a_sweep00_4 = True
rename_settlement_id_to_settlement_ref_a_sweep00_5 = True
rename_settlement_id_to_settlement_ref_a_sweep00_6 = True
rename_settlement_id_to_settlement_ref_a_sweep00_7 = True
rename_settlement_id_to_settlement_ref_a_sweep00_8 = True
rename_settlement_id_to_settlement_ref_a_sweep00_9 = True
rename_settlement_id_to_settlement_ref_a_sweep00_10 = True
rename_settlement_id_to_settlement_ref_a_sweep00_11 = True
rename_settlement_id_to_settlement_ref_a_sweep00_12 = True
rename_settlement_id_to_settlement_ref_a_sweep00_13 = True
rename_settlement_id_to_settlement_ref_a_sweep00_14 = True
rename_settlement_id_to_settlement_ref_a_sweep00_15 = True
rename_settlement_id_to_settlement_ref_a_sweep00_16 = True
rename_settlement_id_to_settlement_ref_a_sweep00_17 = True
rename_settlement_id_to_settlement_ref_a_sweep00_18 = True
rename_settlement_id_to_settlement_ref_a_sweep00_19 = True
rename_settlement_id_to_settlement_ref_a_sweep00_20 = True
rename_settlement_id_to_settlement_ref_a_sweep00_21 = True
rename_settlement_id_to_settlement_ref_a_sweep00_22 = True
rename_settlement_id_to_settlement_ref_a_sweep00_23 = True
rename_settlement_id_to_settlement_ref_a_sweep00_24 = True
rename_settlement_id_to_settlement_ref_a_sweep00_25 = True
rename_settlement_id_to_settlement_ref_a_sweep00_26 = True
rename_settlement_id_to_settlement_ref_a_sweep00_27 = True
rename_settlement_id_to_settlement_ref_a_sweep00_28 = True
rename_settlement_id_to_settlement_ref_a_sweep00_29 = True
rename_settlement_id_to_settlement_ref_a_sweep00_30 = True
rename_settlement_id_to_settlement_ref_a_sweep00_31 = True
rename_settlement_id_to_settlement_ref_a_sweep00_32 = True
rename_settlement_id_to_settlement_ref_a_sweep00_33 = True
rename_settlement_id_to_settlement_ref_a_sweep00_34 = True
rename_settlement_id_to_settlement_ref_a_sweep00_35 = True
rename_settlement_id_to_settlement_ref_a_sweep00_36 = True
rename_settlement_id_to_settlement_ref_a_sweep00_37 = True
rename_settlement_id_to_settlement_ref_a_sweep00_38 = True
rename_settlement_id_to_settlement_ref_a_sweep00_39 = True
rename_settlement_id_to_settlement_ref_a_sweep00_40 = True
rename_settlement_id_to_settlement_ref_a_sweep00_41 = True
rename_settlement_id_to_settlement_ref_a_sweep00_42 = True
rename_settlement_id_to_settlement_ref_a_sweep00_43 = True
rename_settlement_id_to_settlement_ref_a_sweep00_44 = True
rename_settlement_id_to_settlement_ref_a_sweep00_45 = True
rename_settlement_id_to_settlement_ref_a_sweep00_46 = True
rename_settlement_id_to_settlement_ref_a_sweep00_47 = True
rename_settlement_id_to_settlement_ref_a_sweep00_48 = True
rename_settlement_id_to_settlement_ref_a_sweep00_49 = True
rename_settlement_id_to_settlement_ref_a_sweep00_50 = True
rename_settlement_id_to_settlement_ref_a_sweep00_51 = True
rename_settlement_id_to_settlement_ref_a_sweep00_52 = True
rename_settlement_id_to_settlement_ref_a_sweep00_53 = True
rename_settlement_id_to_settlement_ref_a_sweep00_54 = True
rename_settlement_id_to_settlement_ref_a_sweep00_55 = True
rename_settlement_id_to_settlement_ref_a_sweep00_56 = True
rename_settlement_id_to_settlement_ref_a_sweep00_57 = True
rename_settlement_id_to_settlement_ref_a_sweep00_58 = True
rename_settlement_id_to_settlement_ref_a_sweep00_59 = True
rename_settlement_id_to_settlement_ref_a_sweep00_60 = True
rename_settlement_id_to_settlement_ref_a_sweep00_61 = True
rename_settlement_id_to_settlement_ref_a_sweep00_62 = True
rename_settlement_id_to_settlement_ref_a_sweep00_63 = True
rename_settlement_id_to_settlement_ref_a_sweep00_64 = True
rename_settlement_id_to_settlement_ref_a_sweep00_65 = True
rename_settlement_id_to_settlement_ref_a_sweep00_66 = True
rename_settlement_id_to_settlement_ref_a_sweep00_67 = True
rename_settlement_id_to_settlement_ref_a_sweep00_68 = True
rename_settlement_id_to_settlement_ref_a_sweep00_69 = True
rename_settlement_id_to_settlement_ref_a_sweep00_70 = True
rename_settlement_id_to_settlement_ref_a_sweep00_71 = True
rename_settlement_id_to_settlement_ref_a_sweep00_72 = True
rename_settlement_id_to_settlement_ref_a_sweep00_73 = True
rename_settlement_id_to_settlement_ref_a_sweep00_74 = True
rename_settlement_id_to_settlement_ref_a_sweep00_75 = True
rename_settlement_id_to_settlement_ref_a_sweep00_76 = True
rename_settlement_id_to_settlement_ref_a_sweep00_77 = True
rename_settlement_id_to_settlement_ref_a_sweep00_78 = True
rename_settlement_id_to_settlement_ref_a_sweep00_79 = True
rename_settlement_id_to_settlement_ref_a_sweep00_80 = True
rename_settlement_id_to_settlement_ref_a_sweep00_81 = True
rename_settlement_id_to_settlement_ref_a_sweep00_82 = True
rename_settlement_id_to_settlement_ref_a_sweep00_83 = True
rename_settlement_id_to_settlement_ref_a_sweep00_84 = True
rename_settlement_id_to_settlement_ref_a_sweep00_85 = True
rename_settlement_id_to_settlement_ref_a_sweep00_86 = True
rename_settlement_id_to_settlement_ref_a_sweep00_87 = True
rename_settlement_id_to_settlement_ref_a_sweep00_88 = True
rename_settlement_id_to_settlement_ref_a_sweep00_89 = True
rename_settlement_id_to_settlement_ref_a_sweep00_90 = True
rename_settlement_id_to_settlement_ref_a_sweep00_91 = True
rename_settlement_id_to_settlement_ref_a_sweep00_92 = True
rename_settlement_id_to_settlement_ref_a_sweep00_93 = True
rename_settlement_id_to_settlement_ref_a_sweep00_94 = True
rename_settlement_id_to_settlement_ref_a_sweep00_95 = True
rename_settlement_id_to_settlement_ref_a_sweep00_96 = True
rename_settlement_id_to_settlement_ref_a_sweep00_97 = True
rename_settlement_id_to_settlement_ref_a_sweep00_98 = True
rename_settlement_id_to_settlement_ref_a_sweep00_99 = True
rename_settlement_id_to_settlement_ref_a_sweep00_100 = True
rename_settlement_id_to_settlement_ref_a_sweep00_101 = True
rename_settlement_id_to_settlement_ref_a_sweep00_102 = True
rename_settlement_id_to_settlement_ref_a_sweep00_103 = True
rename_settlement_id_to_settlement_ref_a_sweep00_104 = True
rename_settlement_id_to_settlement_ref_a_sweep00_105 = True
rename_settlement_id_to_settlement_ref_a_sweep00_106 = True
rename_settlement_id_to_settlement_ref_a_sweep00_107 = True
rename_settlement_id_to_settlement_ref_a_sweep00_108 = True
rename_settlement_id_to_settlement_ref_a_sweep00_109 = True
rename_settlement_id_to_settlement_ref_a_sweep00_110 = True
rename_settlement_id_to_settlement_ref_a_sweep00_111 = True
rename_settlement_id_to_settlement_ref_a_sweep00_112 = True
rename_settlement_id_to_settlement_ref_a_sweep00_113 = True
rename_settlement_id_to_settlement_ref_a_sweep00_114 = True
rename_settlement_id_to_settlement_ref_a_sweep00_115 = True
rename_settlement_id_to_settlement_ref_a_sweep00_116 = True
rename_settlement_id_to_settlement_ref_a_sweep00_117 = True
rename_settlement_id_to_settlement_ref_a_sweep00_118 = True
rename_settlement_id_to_settlement_ref_a_sweep00_119 = True
rename_settlement_id_to_settlement_ref_a_sweep00_120 = True
