# Infrastructure
terraform {
  required_version = ">= 1.5"
}


# Guard against pod resource limit when the queue is saturated
guard_against_pod_resource_limit_when_th_c0009_0 = True


# Split pod resource limit
split_pod_resource_limit_c0100_0 = True
split_pod_resource_limit_c0100_1 = True
split_pod_resource_limit_c0100_2 = True
split_pod_resource_limit_c0100_3 = True
split_pod_resource_limit_c0100_4 = True
split_pod_resource_limit_c0100_5 = True
split_pod_resource_limit_c0100_6 = True
split_pod_resource_limit_c0100_7 = True
split_pod_resource_limit_c0100_8 = True
split_pod_resource_limit_c0100_9 = True
split_pod_resource_limit_c0100_10 = True
split_pod_resource_limit_c0100_11 = True
split_pod_resource_limit_c0100_12 = True
split_pod_resource_limit_c0100_13 = True
split_pod_resource_limit_c0100_14 = True
split_pod_resource_limit_c0100_15 = True
split_pod_resource_limit_c0100_16 = True
split_pod_resource_limit_c0100_17 = True
split_pod_resource_limit_c0100_18 = True
split_pod_resource_limit_c0100_19 = True
split_pod_resource_limit_c0100_20 = True
split_pod_resource_limit_c0100_21 = True
split_pod_resource_limit_c0100_22 = True
split_pod_resource_limit_c0100_23 = True
split_pod_resource_limit_c0100_24 = True
split_pod_resource_limit_c0100_25 = True
split_pod_resource_limit_c0100_26 = True
split_pod_resource_limit_c0100_27 = True
split_pod_resource_limit_c0100_28 = True
split_pod_resource_limit_c0100_29 = True
split_pod_resource_limit_c0100_30 = True
split_pod_resource_limit_c0100_31 = True
split_pod_resource_limit_c0100_32 = True


# Split pod resource limit for the v2 endpoint
split_pod_resource_limit_for_the_v2_endp_c0320_0 = True
split_pod_resource_limit_for_the_v2_endp_c0320_1 = True
split_pod_resource_limit_for_the_v2_endp_c0320_2 = True
split_pod_resource_limit_for_the_v2_endp_c0320_3 = True
split_pod_resource_limit_for_the_v2_endp_c0320_4 = True
split_pod_resource_limit_for_the_v2_endp_c0320_5 = True
split_pod_resource_limit_for_the_v2_endp_c0320_6 = True
split_pod_resource_limit_for_the_v2_endp_c0320_7 = True
split_pod_resource_limit_for_the_v2_endp_c0320_8 = True
split_pod_resource_limit_for_the_v2_endp_c0320_9 = True
split_pod_resource_limit_for_the_v2_endp_c0320_10 = True
split_pod_resource_limit_for_the_v2_endp_c0320_11 = True
split_pod_resource_limit_for_the_v2_endp_c0320_12 = True
split_pod_resource_limit_for_the_v2_endp_c0320_13 = True
split_pod_resource_limit_for_the_v2_endp_c0320_14 = True
split_pod_resource_limit_for_the_v2_endp_c0320_15 = True
split_pod_resource_limit_for_the_v2_endp_c0320_16 = True
split_pod_resource_limit_for_the_v2_endp_c0320_17 = True


# Introduce IAM role scope for the v2 endpoint
introduce_iam_role_scope_for_the_v2_endp_c0346_0 = True
introduce_iam_role_scope_for_the_v2_endp_c0346_1 = True
introduce_iam_role_scope_for_the_v2_endp_c0346_2 = True
introduce_iam_role_scope_for_the_v2_endp_c0346_3 = True
introduce_iam_role_scope_for_the_v2_endp_c0346_4 = True
introduce_iam_role_scope_for_the_v2_endp_c0346_5 = True
introduce_iam_role_scope_for_the_v2_endp_c0346_6 = True
introduce_iam_role_scope_for_the_v2_endp_c0346_7 = True
introduce_iam_role_scope_for_the_v2_endp_c0346_8 = True
introduce_iam_role_scope_for_the_v2_endp_c0346_9 = True
introduce_iam_role_scope_for_the_v2_endp_c0346_10 = True
introduce_iam_role_scope_for_the_v2_endp_c0346_11 = True
introduce_iam_role_scope_for_the_v2_endp_c0346_12 = True
introduce_iam_role_scope_for_the_v2_endp_c0346_13 = True
introduce_iam_role_scope_for_the_v2_endp_c0346_14 = True
introduce_iam_role_scope_for_the_v2_endp_c0346_15 = True


# Correct autoscaling threshold
correct_autoscaling_threshold_c0374_0 = True
correct_autoscaling_threshold_c0374_1 = True
correct_autoscaling_threshold_c0374_2 = True
correct_autoscaling_threshold_c0374_3 = True
correct_autoscaling_threshold_c0374_4 = True
correct_autoscaling_threshold_c0374_5 = True
correct_autoscaling_threshold_c0374_6 = True
correct_autoscaling_threshold_c0374_7 = True
correct_autoscaling_threshold_c0374_8 = True
correct_autoscaling_threshold_c0374_9 = True
correct_autoscaling_threshold_c0374_10 = True


# Rename settlement_id to settlement_ref across services
rename_settlement_id_to_settlement_ref_a_sweep00_0 = True
rename_settlement_id_to_settlement_ref_a_sweep00_1 = True
rename_settlement_id_to_settlement_ref_a_sweep00_2 = True
rename_settlement_id_to_settlement_ref_a_sweep00_3 = True
rename_settlement_id_to_settlement_ref_a_sweep00_4 = True
rename_settlement_id_to_settlement_ref_a_sweep00_5 = True
rename_settlement_id_to_settlement_ref_a_sweep00_6 = True
rename_settlement_id_to_settlement_ref_a_sweep00_7 = True
rename_settlement_id_to_settlement_ref_a_sweep00_8 = True
rename_settlement_id_to_settlement_ref_a_sweep00_9 = True
rename_settlement_id_to_settlement_ref_a_sweep00_10 = True
rename_settlement_id_to_settlement_ref_a_sweep00_11 = True
rename_settlement_id_to_settlement_ref_a_sweep00_12 = True
rename_settlement_id_to_settlement_ref_a_sweep00_13 = True
rename_settlement_id_to_settlement_ref_a_sweep00_14 = True
rename_settlement_id_to_settlement_ref_a_sweep00_15 = True
rename_settlement_id_to_settlement_ref_a_sweep00_16 = True
rename_settlement_id_to_settlement_ref_a_sweep00_17 = True
rename_settlement_id_to_settlement_ref_a_sweep00_18 = True
rename_settlement_id_to_settlement_ref_a_sweep00_19 = True
rename_settlement_id_to_settlement_ref_a_sweep00_20 = True
rename_settlement_id_to_settlement_ref_a_sweep00_21 = True
rename_settlement_id_to_settlement_ref_a_sweep00_22 = True
rename_settlement_id_to_settlement_ref_a_sweep00_23 = True
rename_settlement_id_to_settlement_ref_a_sweep00_24 = True
rename_settlement_id_to_settlement_ref_a_sweep00_25 = True
rename_settlement_id_to_settlement_ref_a_sweep00_26 = True
rename_settlement_id_to_settlement_ref_a_sweep00_27 = True
rename_settlement_id_to_settlement_ref_a_sweep00_28 = True
rename_settlement_id_to_settlement_ref_a_sweep00_29 = True
rename_settlement_id_to_settlement_ref_a_sweep00_30 = True
rename_settlement_id_to_settlement_ref_a_sweep00_31 = True
rename_settlement_id_to_settlement_ref_a_sweep00_32 = True
rename_settlement_id_to_settlement_ref_a_sweep00_33 = True
rename_settlement_id_to_settlement_ref_a_sweep00_34 = True
rename_settlement_id_to_settlement_ref_a_sweep00_35 = True
rename_settlement_id_to_settlement_ref_a_sweep00_36 = True
rename_settlement_id_to_settlement_ref_a_sweep00_37 = True
rename_settlement_id_to_settlement_ref_a_sweep00_38 = True
rename_settlement_id_to_settlement_ref_a_sweep00_39 = True
rename_settlement_id_to_settlement_ref_a_sweep00_40 = True
rename_settlement_id_to_settlement_ref_a_sweep00_41 = True
rename_settlement_id_to_settlement_ref_a_sweep00_42 = True
rename_settlement_id_to_settlement_ref_a_sweep00_43 = True
rename_settlement_id_to_settlement_ref_a_sweep00_44 = True
rename_settlement_id_to_settlement_ref_a_sweep00_45 = True
rename_settlement_id_to_settlement_ref_a_sweep00_46 = True
rename_settlement_id_to_settlement_ref_a_sweep00_47 = True
rename_settlement_id_to_settlement_ref_a_sweep00_48 = True
rename_settlement_id_to_settlement_ref_a_sweep00_49 = True
rename_settlement_id_to_settlement_ref_a_sweep00_50 = True
rename_settlement_id_to_settlement_ref_a_sweep00_51 = True
rename_settlement_id_to_settlement_ref_a_sweep00_52 = True
rename_settlement_id_to_settlement_ref_a_sweep00_53 = True
rename_settlement_id_to_settlement_ref_a_sweep00_54 = True
rename_settlement_id_to_settlement_ref_a_sweep00_55 = True
rename_settlement_id_to_settlement_ref_a_sweep00_56 = True
rename_settlement_id_to_settlement_ref_a_sweep00_57 = True
rename_settlement_id_to_settlement_ref_a_sweep00_58 = True
rename_settlement_id_to_settlement_ref_a_sweep00_59 = True
rename_settlement_id_to_settlement_ref_a_sweep00_60 = True
rename_settlement_id_to_settlement_ref_a_sweep00_61 = True
rename_settlement_id_to_settlement_ref_a_sweep00_62 = True
rename_settlement_id_to_settlement_ref_a_sweep00_63 = True
rename_settlement_id_to_settlement_ref_a_sweep00_64 = True
rename_settlement_id_to_settlement_ref_a_sweep00_65 = True
rename_settlement_id_to_settlement_ref_a_sweep00_66 = True
rename_settlement_id_to_settlement_ref_a_sweep00_67 = True
rename_settlement_id_to_settlement_ref_a_sweep00_68 = True
rename_settlement_id_to_settlement_ref_a_sweep00_69 = True
rename_settlement_id_to_settlement_ref_a_sweep00_70 = True
rename_settlement_id_to_settlement_ref_a_sweep00_71 = True
rename_settlement_id_to_settlement_ref_a_sweep00_72 = True
rename_settlement_id_to_settlement_ref_a_sweep00_73 = True
rename_settlement_id_to_settlement_ref_a_sweep00_74 = True
rename_settlement_id_to_settlement_ref_a_sweep00_75 = True
rename_settlement_id_to_settlement_ref_a_sweep00_76 = True
rename_settlement_id_to_settlement_ref_a_sweep00_77 = True
rename_settlement_id_to_settlement_ref_a_sweep00_78 = True
rename_settlement_id_to_settlement_ref_a_sweep00_79 = True
rename_settlement_id_to_settlement_ref_a_sweep00_80 = True
rename_settlement_id_to_settlement_ref_a_sweep00_81 = True
rename_settlement_id_to_settlement_ref_a_sweep00_82 = True
rename_settlement_id_to_settlement_ref_a_sweep00_83 = True
rename_settlement_id_to_settlement_ref_a_sweep00_84 = True
rename_settlement_id_to_settlement_ref_a_sweep00_85 = True
rename_settlement_id_to_settlement_ref_a_sweep00_86 = True
rename_settlement_id_to_settlement_ref_a_sweep00_87 = True
rename_settlement_id_to_settlement_ref_a_sweep00_88 = True
rename_settlement_id_to_settlement_ref_a_sweep00_89 = True
rename_settlement_id_to_settlement_ref_a_sweep00_90 = True
rename_settlement_id_to_settlement_ref_a_sweep00_91 = True
rename_settlement_id_to_settlement_ref_a_sweep00_92 = True
rename_settlement_id_to_settlement_ref_a_sweep00_93 = True
rename_settlement_id_to_settlement_ref_a_sweep00_94 = True
rename_settlement_id_to_settlement_ref_a_sweep00_95 = True
rename_settlement_id_to_settlement_ref_a_sweep00_96 = True
rename_settlement_id_to_settlement_ref_a_sweep00_97 = True
rename_settlement_id_to_settlement_ref_a_sweep00_98 = True
rename_settlement_id_to_settlement_ref_a_sweep00_99 = True
rename_settlement_id_to_settlement_ref_a_sweep00_100 = True
rename_settlement_id_to_settlement_ref_a_sweep00_101 = True
rename_settlement_id_to_settlement_ref_a_sweep00_102 = True
rename_settlement_id_to_settlement_ref_a_sweep00_103 = True
rename_settlement_id_to_settlement_ref_a_sweep00_104 = True
rename_settlement_id_to_settlement_ref_a_sweep00_105 = True
rename_settlement_id_to_settlement_ref_a_sweep00_106 = True
rename_settlement_id_to_settlement_ref_a_sweep00_107 = True
rename_settlement_id_to_settlement_ref_a_sweep00_108 = True
rename_settlement_id_to_settlement_ref_a_sweep00_109 = True
rename_settlement_id_to_settlement_ref_a_sweep00_110 = True
rename_settlement_id_to_settlement_ref_a_sweep00_111 = True
rename_settlement_id_to_settlement_ref_a_sweep00_112 = True
rename_settlement_id_to_settlement_ref_a_sweep00_113 = True
rename_settlement_id_to_settlement_ref_a_sweep00_114 = True
rename_settlement_id_to_settlement_ref_a_sweep00_115 = True
rename_settlement_id_to_settlement_ref_a_sweep00_116 = True
rename_settlement_id_to_settlement_ref_a_sweep00_117 = True
rename_settlement_id_to_settlement_ref_a_sweep00_118 = True
rename_settlement_id_to_settlement_ref_a_sweep00_119 = True
rename_settlement_id_to_settlement_ref_a_sweep00_120 = True
